// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"github.com/pickle-pw/twitch-harbor/internal/api"
	"github.com/pickle-pw/twitch-harbor/internal/clients"
	"github.com/pickle-pw/twitch-harbor/internal/handler"
	"github.com/pickle-pw/twitch-harbor/internal/service"
	"github.com/pickle-pw/twitch-harbor/internal/storage"
)

func InitializeService(ctx context.Context) (api.TwitchHarborAPI, error) {
	var err error
	oryAPI, err := kessoku.Provide(clients.NewOryAPI).Fn()(ctx)
	if err != nil {
		var zero api.TwitchHarborAPI
		return zero, err
	}
	var err0 error
	relationalStorage, _, err0 := kessoku.Provide(storage.NewRelationalStorage).Fn()(ctx)
	if err0 != nil {
		var zero api.TwitchHarborAPI
		return zero, err0
	}
	twitchHelixClient := kessoku.Provide(clients.NewTwitchHelixClient).Fn()(ctx)
	twitchAuthService := kessoku.Provide(service.NewTwitchAuthService).Fn()(relationalStorage, oryAPI)
	orderService := kessoku.Provide(service.NewOrderService).Fn()(relationalStorage)
	eventsubService := kessoku.Provide(service.NewEventsubService).Fn()(twitchHelixClient, relationalStorage)
	twitchRewardService := kessoku.Provide(service.NewTwitchRewardService).Fn()(relationalStorage, twitchHelixClient, twitchAuthService)
	webhookHandler := kessoku.Provide(handler.NewWebhookHandler).Fn()(twitchAuthService, oryAPI, eventsubService)
	broadcasterService := kessoku.Provide(service.NewBroadcasterService).Fn()(relationalStorage, oryAPI, twitchAuthService, eventsubService, twitchRewardService)
	broadcasterHandler := kessoku.Provide(handler.NewBroadcasterHandler).Fn()(broadcasterService, twitchAuthService, twitchRewardService, orderService, eventsubService)
	twitchEventService := kessoku.Provide(service.NewTwitchEventService).Fn()(twitchAuthService, eventsubService, relationalStorage, broadcasterService, orderService)
	twitchWSService := kessoku.Provide(service.NewTwitchWSService).Fn()(relationalStorage, twitchEventService)
	twitchHarborAPI := kessoku.Provide(api.NewTwitchHarborAPI).Fn()(webhookHandler, broadcasterHandler, oryAPI, twitchWSService)
	return twitchHarborAPI, nil
}
