// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/pickle-pw/twitch-harbor/internal/api"
	"github.com/pickle-pw/twitch-harbor/internal/clients"
	"github.com/pickle-pw/twitch-harbor/internal/handler"
	"github.com/pickle-pw/twitch-harbor/internal/service"
	"github.com/pickle-pw/twitch-harbor/internal/storage"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeService(ctx context.Context) (api.TwitchHarborAPI, func(), error) {
	relationalStorage, cleanup, err := storage.NewRelationalStorage(ctx)
	if err != nil {
		return nil, nil, err
	}
	oryAPI, err := clients.NewOryAPI(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	twitchAuthService := service.NewTwitchAuthService(relationalStorage, oryAPI)
	twitchHelixClient := clients.NewTwitchHelixClient(ctx)
	eventsubService := service.NewEventsubService(twitchHelixClient, relationalStorage)
	webhookHandler := handler.NewWebhookHandler(twitchAuthService, oryAPI, eventsubService)
	twitchRewardService := service.NewTwitchRewardService(relationalStorage, twitchHelixClient, twitchAuthService)
	broadcasterService := service.NewBroadcasterService(relationalStorage, oryAPI, twitchAuthService, eventsubService, twitchRewardService)
	orderService := service.NewOrderService(relationalStorage)
	broadcasterHandler := handler.NewBroadcasterHandler(broadcasterService, twitchAuthService, twitchRewardService, orderService, eventsubService)
	twitchEventService := service.NewTwitchEventService(twitchAuthService, eventsubService, relationalStorage, broadcasterService, orderService)
	twitchWSService := service.NewTwitchWSService(relationalStorage, twitchEventService)
	twitchHarborAPI := api.NewTwitchHarborAPI(webhookHandler, broadcasterHandler, oryAPI, twitchWSService)
	return twitchHarborAPI, func() {
		cleanup()
	}, nil
}
