// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type BroadcasterTrackedReward struct {
	BroadcasterID   string     `json:"broadcaster_id"`
	TrackedRewardID string     `json:"tracked_reward_id"`
	Category        string     `json:"category"`
	CreatedAt       *time.Time `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
	UpdatedBy       uuid.UUID  `json:"updated_by"`
}

type EventsubSubscription struct {
	ID           uuid.UUID  `json:"id"`
	ConnectionID *uuid.UUID `json:"connection_id"`
	IdentityID   uuid.UUID  `json:"identity_id"`
	ReferenceID  *string    `json:"reference_id"`
	EventType    string     `json:"event_type"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
	Status       string     `json:"status"`
}

type TwitchAuthorization struct {
	IdentityID    uuid.UUID  `json:"identity_id"`
	BroadcasterID string     `json:"broadcaster_id"`
	AccessToken   string     `json:"access_token"`
	RefreshToken  string     `json:"refresh_token"`
	ExpiresAt     time.Time  `json:"expires_at"`
	CreatedAt     *time.Time `json:"created_at"`
	UpdatedAt     *time.Time `json:"updated_at"`
}

type TwitchNotification struct {
	ID             uuid.UUID  `json:"id"`
	IdentityID     uuid.UUID  `json:"identity_id"`
	SubscriptionID *uuid.UUID `json:"subscription_id"`
	MessageType    string     `json:"message_type"`
	Payload        []byte     `json:"payload"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
	RetryCount     int32      `json:"retry_count"`
	Status         string     `json:"status"`
}

type WebsocketConnection struct {
	ID                uuid.UUID `json:"id"`
	SessionID         *string   `json:"session_id"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	LastPing          time.Time `json:"last_ping"`
	Status            string    `json:"status"`
	ErrorCount        int32     `json:"error_count"`
	ErrorMessage      string    `json:"error_message"`
	SubscriptionCount int32     `json:"subscription_count"`
	IdentityID        uuid.UUID `json:"identity_id"`
}
