// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: twitch_notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertTwitchNotification = `-- name: InsertTwitchNotification :one
INSERT INTO "twitch_notifications" (
    "identity_id",
    "subscription_id",
    "message_type",
    "payload",
    "status"
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::jsonb,
    $5::text
)
RETURNING id, identity_id, subscription_id, message_type, payload, created_at, updated_at, retry_count, status
`

type InsertTwitchNotificationParams struct {
	IdentityID     uuid.UUID  `json:"identity_id"`
	SubscriptionID *uuid.UUID `json:"subscription_id"`
	MessageType    string     `json:"message_type"`
	Payload        []byte     `json:"payload"`
	Status         string     `json:"status"`
}

func (q *Queries) InsertTwitchNotification(ctx context.Context, arg InsertTwitchNotificationParams) (*TwitchNotification, error) {
	row := q.db.QueryRow(ctx, insertTwitchNotification,
		arg.IdentityID,
		arg.SubscriptionID,
		arg.MessageType,
		arg.Payload,
		arg.Status,
	)
	var i TwitchNotification
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.SubscriptionID,
		&i.MessageType,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
		&i.Status,
	)
	return &i, err
}

const updateTwitchNotificationStatus = `-- name: UpdateTwitchNotificationStatus :exec
UPDATE "twitch_notifications"
SET "status" = $1::text,
    "retry_count" = $2::int,
    "updated_at" = now()
WHERE "id" = $3::uuid
`

type UpdateTwitchNotificationStatusParams struct {
	Status     string    `json:"status"`
	RetryCount int32     `json:"retry_count"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTwitchNotificationStatus(ctx context.Context, arg UpdateTwitchNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateTwitchNotificationStatus, arg.Status, arg.RetryCount, arg.ID)
	return err
}
