// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: twitch_authorizations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findTwitchAuthorizationByBroadcasterID = `-- name: FindTwitchAuthorizationByBroadcasterID :one
SELECT identity_id, broadcaster_id, access_token, refresh_token, expires_at, created_at, updated_at
FROM twitch_authorizations
WHERE broadcaster_id = $1::text
`

func (q *Queries) FindTwitchAuthorizationByBroadcasterID(ctx context.Context, broadcasterID string) (*TwitchAuthorization, error) {
	row := q.db.QueryRow(ctx, findTwitchAuthorizationByBroadcasterID, broadcasterID)
	var i TwitchAuthorization
	err := row.Scan(
		&i.IdentityID,
		&i.BroadcasterID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findTwitchAuthorizationByIdentityID = `-- name: FindTwitchAuthorizationByIdentityID :one
SELECT identity_id, broadcaster_id, access_token, refresh_token, expires_at, created_at, updated_at
FROM twitch_authorizations
WHERE identity_id = $1::uuid
`

func (q *Queries) FindTwitchAuthorizationByIdentityID(ctx context.Context, identityID uuid.UUID) (*TwitchAuthorization, error) {
	row := q.db.QueryRow(ctx, findTwitchAuthorizationByIdentityID, identityID)
	var i TwitchAuthorization
	err := row.Scan(
		&i.IdentityID,
		&i.BroadcasterID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertTwitchAuthorization = `-- name: InsertTwitchAuthorization :one
INSERT INTO twitch_authorizations (
        identity_id,
        broadcaster_id,
        access_token,
        refresh_token,
        expires_at
    )
VALUES (
        $1::uuid,
        $2::text,
        $3::text,
        $4::text,
        $5::timestamptz
    ) ON CONFLICT (identity_id) DO
UPDATE
SET broadcaster_id = $2::text,
    access_token = $3::text,
    refresh_token = $4::text,
    expires_at = $5::timestamptz
RETURNING identity_id, broadcaster_id, access_token, refresh_token, expires_at, created_at, updated_at
`

type InsertTwitchAuthorizationParams struct {
	IdentityID    uuid.UUID `json:"identity_id"`
	BroadcasterID string    `json:"broadcaster_id"`
	AccessToken   string    `json:"access_token"`
	RefreshToken  string    `json:"refresh_token"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) InsertTwitchAuthorization(ctx context.Context, arg InsertTwitchAuthorizationParams) (*TwitchAuthorization, error) {
	row := q.db.QueryRow(ctx, insertTwitchAuthorization,
		arg.IdentityID,
		arg.BroadcasterID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i TwitchAuthorization
	err := row.Scan(
		&i.IdentityID,
		&i.BroadcasterID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateTwitchAuthorizationByIdentityID = `-- name: UpdateTwitchAuthorizationByIdentityID :one
UPDATE twitch_authorizations
SET access_token = $1::text,
    refresh_token = $2::text,
    expires_at = $3::timestamptz
WHERE identity_id = $4::uuid
RETURNING identity_id, broadcaster_id, access_token, refresh_token, expires_at, created_at, updated_at
`

type UpdateTwitchAuthorizationByIdentityIDParams struct {
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	IdentityID   uuid.UUID `json:"identity_id"`
}

func (q *Queries) UpdateTwitchAuthorizationByIdentityID(ctx context.Context, arg UpdateTwitchAuthorizationByIdentityIDParams) (*TwitchAuthorization, error) {
	row := q.db.QueryRow(ctx, updateTwitchAuthorizationByIdentityID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.IdentityID,
	)
	var i TwitchAuthorization
	err := row.Scan(
		&i.IdentityID,
		&i.BroadcasterID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
