// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: collections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteCollectionByID = `-- name: DeleteCollectionByID :exec
DELETE 
FROM "collections" 
WHERE "id" = $1
`

func (q *Queries) DeleteCollectionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollectionByID, id)
	return err
}

const deleteCollectionItemByID = `-- name: DeleteCollectionItemByID :exec
DELETE 
FROM "collection_items" 
WHERE "id" = $1
`

func (q *Queries) DeleteCollectionItemByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollectionItemByID, id)
	return err
}

const findCollectionByID = `-- name: FindCollectionByID :one
SELECT id, created_at, created_by, updated_at, updated_by, name, user_id 
FROM "collections" 
WHERE "id" = $1
`

func (q *Queries) FindCollectionByID(ctx context.Context, id uuid.UUID) (*Collection, error) {
	row := q.db.QueryRow(ctx, findCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Name,
		&i.UserID,
	)
	return &i, err
}

const findCollectionItemByID = `-- name: FindCollectionItemByID :one
SELECT id, collection_id, note_id, category, created_at, created_by 
FROM "collection_items" 
WHERE "id" = $1
`

func (q *Queries) FindCollectionItemByID(ctx context.Context, id uuid.UUID) (*CollectionItem, error) {
	row := q.db.QueryRow(ctx, findCollectionItemByID, id)
	var i CollectionItem
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.NoteID,
		&i.Category,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return &i, err
}

const findCollectionItemsByCollectionID = `-- name: FindCollectionItemsByCollectionID :many
SELECT id, collection_id, note_id, category, created_at, created_by 
FROM "collection_items" 
WHERE "collection_id" = $1
`

func (q *Queries) FindCollectionItemsByCollectionID(ctx context.Context, collectionID uuid.UUID) ([]*CollectionItem, error) {
	rows, err := q.db.Query(ctx, findCollectionItemsByCollectionID, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CollectionItem
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.NoteID,
			&i.Category,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCollectionItemsByUserID = `-- name: FindCollectionItemsByUserID :many
SELECT ci.id, ci.collection_id, ci.note_id, ci.category, ci.created_at, ci.created_by 
FROM "collection_items" ci
INNER JOIN "collections" c ON ci."collection_id" = c."id"
WHERE c."user_id" = $1
`

func (q *Queries) FindCollectionItemsByUserID(ctx context.Context, userID uuid.UUID) ([]*CollectionItem, error) {
	rows, err := q.db.Query(ctx, findCollectionItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CollectionItem
	for rows.Next() {
		var i CollectionItem
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.NoteID,
			&i.Category,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCollectionsByUserID = `-- name: FindCollectionsByUserID :many
SELECT id, created_at, created_by, updated_at, updated_by, name, user_id 
FROM "collections" 
WHERE "user_id" = $1
`

func (q *Queries) FindCollectionsByUserID(ctx context.Context, userID uuid.UUID) ([]*Collection, error) {
	rows, err := q.db.Query(ctx, findCollectionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Name,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCollection = `-- name: InsertCollection :one
INSERT INTO "collections" (
    "created_by", 
    "updated_by", 
    "name", 
    "user_id"
) VALUES ($1, $2, $3, $4)
RETURNING id, created_at, created_by, updated_at, updated_by, name, user_id
`

type InsertCollectionParams struct {
	CreatedBy uuid.UUID `json:"created_by"`
	UpdatedBy uuid.UUID `json:"updated_by"`
	Name      string    `json:"name"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) InsertCollection(ctx context.Context, arg InsertCollectionParams) (*Collection, error) {
	row := q.db.QueryRow(ctx, insertCollection,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.Name,
		arg.UserID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Name,
		&i.UserID,
	)
	return &i, err
}

const insertCollectionItem = `-- name: InsertCollectionItem :one
INSERT INTO "collection_items" (
    "collection_id", 
    "note_id", 
    "category",
    "created_by"
) VALUES ($1, $2, $3, $4)
RETURNING id, collection_id, note_id, category, created_at, created_by
`

type InsertCollectionItemParams struct {
	CollectionID uuid.UUID       `json:"collection_id"`
	NoteID       uuid.UUID       `json:"note_id"`
	Category     ContentCategory `json:"category"`
	CreatedBy    uuid.UUID       `json:"created_by"`
}

func (q *Queries) InsertCollectionItem(ctx context.Context, arg InsertCollectionItemParams) (*CollectionItem, error) {
	row := q.db.QueryRow(ctx, insertCollectionItem,
		arg.CollectionID,
		arg.NoteID,
		arg.Category,
		arg.CreatedBy,
	)
	var i CollectionItem
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.NoteID,
		&i.Category,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return &i, err
}
