// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: eventsub_subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findActiveSubscriptionsByEventType = `-- name: FindActiveSubscriptionsByEventType :many
SELECT es.id, es.connection_id, es.identity_id, es.reference_id, es.event_type, es.created_at, es.updated_at, es.status
FROM eventsub_subscriptions es
LEFT JOIN websocket_connections wc ON wc.id = es.connection_id
WHERE event_type = $1::text
    AND es.status = 'subscribed'
    AND es.connection_id IS NOT NULL
    AND wc.updated_at >= NOW() - INTERVAL '5 minutes'
    AND wc.status = 'active'
    AND es.identity_id = $2::uuid
`

type FindActiveSubscriptionsByEventTypeParams struct {
	EventType  string    `json:"event_type"`
	IdentityID uuid.UUID `json:"identity_id"`
}

func (q *Queries) FindActiveSubscriptionsByEventType(ctx context.Context, arg FindActiveSubscriptionsByEventTypeParams) ([]*EventsubSubscription, error) {
	rows, err := q.db.Query(ctx, findActiveSubscriptionsByEventType, arg.EventType, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EventsubSubscription{}
	for rows.Next() {
		var i EventsubSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.IdentityID,
			&i.ReferenceID,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventSubscriptionsByStatus = `-- name: FindEventSubscriptionsByStatus :many
SELECT id, connection_id, identity_id, reference_id, event_type, created_at, updated_at, status
FROM eventsub_subscriptions
WHERE status = $1::text
`

func (q *Queries) FindEventSubscriptionsByStatus(ctx context.Context, status string) ([]*EventsubSubscription, error) {
	rows, err := q.db.Query(ctx, findEventSubscriptionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EventsubSubscription{}
	for rows.Next() {
		var i EventsubSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.IdentityID,
			&i.ReferenceID,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventsubSubscriptionByIdentityID = `-- name: FindEventsubSubscriptionByIdentityID :many
SELECT id, connection_id, identity_id, reference_id, event_type, created_at, updated_at, status
FROM eventsub_subscriptions
WHERE identity_id = $1::uuid
`

func (q *Queries) FindEventsubSubscriptionByIdentityID(ctx context.Context, identityID uuid.UUID) ([]*EventsubSubscription, error) {
	rows, err := q.db.Query(ctx, findEventsubSubscriptionByIdentityID, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EventsubSubscription{}
	for rows.Next() {
		var i EventsubSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.IdentityID,
			&i.ReferenceID,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventsubSubscriptionByReferenceID = `-- name: FindEventsubSubscriptionByReferenceID :one
SELECT id, connection_id, identity_id, reference_id, event_type, created_at, updated_at, status
FROM eventsub_subscriptions
WHERE reference_id = $1::text
`

func (q *Queries) FindEventsubSubscriptionByReferenceID(ctx context.Context, referenceID string) (*EventsubSubscription, error) {
	row := q.db.QueryRow(ctx, findEventsubSubscriptionByReferenceID, referenceID)
	var i EventsubSubscription
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.IdentityID,
		&i.ReferenceID,
		&i.EventType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return &i, err
}

const findEventsubSubscriptionsAssignedToConnectionID = `-- name: FindEventsubSubscriptionsAssignedToConnectionID :many
SELECT id, connection_id, identity_id, reference_id, event_type, created_at, updated_at, status
FROM eventsub_subscriptions
WHERE connection_id = $1::uuid
    AND status = 'assigned'
`

func (q *Queries) FindEventsubSubscriptionsAssignedToConnectionID(ctx context.Context, connectionID uuid.UUID) ([]*EventsubSubscription, error) {
	rows, err := q.db.Query(ctx, findEventsubSubscriptionsAssignedToConnectionID, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EventsubSubscription{}
	for rows.Next() {
		var i EventsubSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.IdentityID,
			&i.ReferenceID,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEventsubSubscriptionsByConnectionID = `-- name: FindEventsubSubscriptionsByConnectionID :many
SELECT id, connection_id, identity_id, reference_id, event_type, created_at, updated_at, status
FROM eventsub_subscriptions
WHERE connection_id = $1::uuid
`

func (q *Queries) FindEventsubSubscriptionsByConnectionID(ctx context.Context, connectionID uuid.UUID) ([]*EventsubSubscription, error) {
	rows, err := q.db.Query(ctx, findEventsubSubscriptionsByConnectionID, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EventsubSubscription{}
	for rows.Next() {
		var i EventsubSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.IdentityID,
			&i.ReferenceID,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPendingEventSubscriptions = `-- name: FindPendingEventSubscriptions :many
SELECT es.id, es.connection_id, es.identity_id, es.reference_id, es.event_type, es.created_at, es.updated_at, es.status
FROM eventsub_subscriptions es
LEFT JOIN websocket_connections wc ON wc.id = es.connection_id
WHERE es.status = 'pending' OR (
    es.status IN ('subscribed', 'assigned')
    AND (wc.status IN ('closed', 'error') OR wc.status IS NULL)
)
`

func (q *Queries) FindPendingEventSubscriptions(ctx context.Context) ([]*EventsubSubscription, error) {
	rows, err := q.db.Query(ctx, findPendingEventSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EventsubSubscription{}
	for rows.Next() {
		var i EventsubSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.IdentityID,
			&i.ReferenceID,
			&i.EventType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEventsubSubscription = `-- name: InsertEventsubSubscription :one
INSERT INTO eventsub_subscriptions (
        id,
        identity_id,
        event_type
    )
VALUES (
        gen_random_uuid(),
        $1::uuid,
        $2::text
    ) ON CONFLICT (id) DO
UPDATE
SET identity_id = $1::uuid,
    event_type = $2::text
RETURNING id, connection_id, identity_id, reference_id, event_type, created_at, updated_at, status
`

type InsertEventsubSubscriptionParams struct {
	IdentityID uuid.UUID `json:"identity_id"`
	EventType  string    `json:"event_type"`
}

func (q *Queries) InsertEventsubSubscription(ctx context.Context, arg InsertEventsubSubscriptionParams) (*EventsubSubscription, error) {
	row := q.db.QueryRow(ctx, insertEventsubSubscription, arg.IdentityID, arg.EventType)
	var i EventsubSubscription
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.IdentityID,
		&i.ReferenceID,
		&i.EventType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return &i, err
}

const updateEventsubSubscriptionConnectionID = `-- name: UpdateEventsubSubscriptionConnectionID :exec
UPDATE eventsub_subscriptions
SET connection_id = $1::uuid,
    updated_at = NOW(),
    status = $2::text
WHERE id = $3::uuid
`

type UpdateEventsubSubscriptionConnectionIDParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	Status       string    `json:"status"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEventsubSubscriptionConnectionID(ctx context.Context, arg UpdateEventsubSubscriptionConnectionIDParams) error {
	_, err := q.db.Exec(ctx, updateEventsubSubscriptionConnectionID, arg.ConnectionID, arg.Status, arg.ID)
	return err
}

const updateEventsubSubscriptionStatus = `-- name: UpdateEventsubSubscriptionStatus :exec
UPDATE eventsub_subscriptions
SET status = $1::text,
    reference_id = $2::text,
    updated_at = NOW()
WHERE id = $3::uuid
`

type UpdateEventsubSubscriptionStatusParams struct {
	Status      string    `json:"status"`
	ReferenceID string    `json:"reference_id"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEventsubSubscriptionStatus(ctx context.Context, arg UpdateEventsubSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateEventsubSubscriptionStatus, arg.Status, arg.ReferenceID, arg.ID)
	return err
}

const updateEventsubSubscriptionsStatusByConnectionID = `-- name: UpdateEventsubSubscriptionsStatusByConnectionID :exec
UPDATE eventsub_subscriptions
SET status = $1::text,
    updated_at = NOW()
WHERE connection_id = $2::uuid
`

type UpdateEventsubSubscriptionsStatusByConnectionIDParams struct {
	Status       string    `json:"status"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) UpdateEventsubSubscriptionsStatusByConnectionID(ctx context.Context, arg UpdateEventsubSubscriptionsStatusByConnectionIDParams) error {
	_, err := q.db.Exec(ctx, updateEventsubSubscriptionsStatusByConnectionID, arg.Status, arg.ConnectionID)
	return err
}
