// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: followers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*)
FROM followers
WHERE user_id = $1::uuid
`

func (q *Queries) CountFollowers(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFollower = `-- name: DeleteFollower :exec
DELETE FROM followers
WHERE user_id = $1::uuid
    AND follower_id = $2::uuid
`

type DeleteFollowerParams struct {
	UserID     uuid.UUID `json:"user_id"`
	FollowerID uuid.UUID `json:"follower_id"`
}

func (q *Queries) DeleteFollower(ctx context.Context, arg DeleteFollowerParams) error {
	_, err := q.db.Exec(ctx, deleteFollower, arg.UserID, arg.FollowerID)
	return err
}

const insertFollower = `-- name: InsertFollower :exec
INSERT INTO followers (user_id, follower_id)
VALUES (
        $1::uuid,
        $2::uuid
    )
`

type InsertFollowerParams struct {
	UserID     uuid.UUID `json:"user_id"`
	FollowerID uuid.UUID `json:"follower_id"`
}

func (q *Queries) InsertFollower(ctx context.Context, arg InsertFollowerParams) error {
	_, err := q.db.Exec(ctx, insertFollower, arg.UserID, arg.FollowerID)
	return err
}

const isFollowing = `-- name: IsFollowing :one
SELECT COUNT(*)
FROM followers
WHERE user_id = $1::uuid
    AND follower_id = $2::uuid
`

type IsFollowingParams struct {
	UserID     uuid.UUID `json:"user_id"`
	FollowerID uuid.UUID `json:"follower_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (int64, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.UserID, arg.FollowerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
