// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_note_orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countOrdersByGameNoteId = `-- name: CountOrdersByGameNoteId :one
SELECT COUNT(*) AS "total"
FROM "game_note_orders"
WHERE "game_note_id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) CountOrdersByGameNoteId(ctx context.Context, gameNoteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByGameNoteId, gameNoteID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertGameNoteOrder = `-- name: InsertGameNoteOrder :one
INSERT INTO "game_note_orders" (
    "game_note_id",
    "order_id",
    "created_by",
    "updated_by"
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING game_note_id, order_id, created_at, created_by, updated_at, updated_by
`

type InsertGameNoteOrderParams struct {
	GameNoteID uuid.UUID `json:"game_note_id"`
	OrderID    uuid.UUID `json:"order_id"`
	CreatedBy  uuid.UUID `json:"created_by"`
	UpdatedBy  uuid.UUID `json:"updated_by"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertGameNoteOrder(ctx context.Context, arg InsertGameNoteOrderParams) (*GameNoteOrder, error) {
	row := q.db.QueryRow(ctx, insertGameNoteOrder,
		arg.GameNoteID,
		arg.OrderID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i GameNoteOrder
	err := row.Scan(
		&i.GameNoteID,
		&i.OrderID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return &i, err
}
