// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: games.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = $1::uuid
`

func (q *Queries) DeleteGame(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const deleteGameLocalization = `-- name: DeleteGameLocalization :exec
DELETE FROM game_localizations WHERE game_id = $1::uuid AND lang = $2::text
`

type DeleteGameLocalizationParams struct {
	GameID uuid.UUID `json:"game_id"`
	Lang   string    `json:"lang"`
}

func (q *Queries) DeleteGameLocalization(ctx context.Context, arg DeleteGameLocalizationParams) error {
	_, err := q.db.Exec(ctx, deleteGameLocalization, arg.GameID, arg.Lang)
	return err
}

const refreshLocalizedGameViews = `-- name: RefreshLocalizedGameViews :exec
SELECT refresh_all_game_views()
`

func (q *Queries) RefreshLocalizedGameViews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshLocalizedGameViews)
	return err
}

const upsertGame = `-- name: UpsertGame :one
INSERT INTO games (
    igdb_id,
    release_date,
    websites
) VALUES (
    $1::bigint,
    $2::timestamptz,
    $3::jsonb
) ON CONFLICT (igdb_id) DO 
UPDATE SET 
    release_date = $2::timestamptz, 
    websites = $3::jsonb,
    updated_at = now()
RETURNING id
`

type UpsertGameParams struct {
	IgdbID      int64     `json:"igdb_id"`
	ReleaseDate time.Time `json:"release_date"`
	Websites    []byte    `json:"websites"`
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertGame, arg.IgdbID, arg.ReleaseDate, arg.Websites)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertGameLocalization = `-- name: UpsertGameLocalization :exec
INSERT INTO game_localizations (
    game_id,
    lang,
    title
) VALUES (
    $1::uuid,
    $2::text,
    $3::text
) ON CONFLICT (game_id, lang) DO 
UPDATE SET 
    title = $3::text,
    updated_at = now()
`

type UpsertGameLocalizationParams struct {
	GameID uuid.UUID `json:"game_id"`
	Lang   string    `json:"lang"`
	Title  string    `json:"title"`
}

func (q *Queries) UpsertGameLocalization(ctx context.Context, arg UpsertGameLocalizationParams) error {
	_, err := q.db.Exec(ctx, upsertGameLocalization, arg.GameID, arg.Lang, arg.Title)
	return err
}
