// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_note_reactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addGameNoteReaction = `-- name: AddGameNoteReaction :exec
INSERT INTO "game_note_reactions" (
    "game_note_id",
    "user_id",
    "emote_id",
    "source",
    "created_by"
) VALUES (
    $1, $2, $3, $4, $5
)
`

type AddGameNoteReactionParams struct {
	GameNoteID uuid.UUID      `json:"game_note_id"`
	UserID     uuid.UUID      `json:"user_id"`
	EmoteID    string         `json:"emote_id"`
	Source     ReactionSource `json:"source"`
	CreatedBy  uuid.UUID      `json:"created_by"`
}

func (q *Queries) AddGameNoteReaction(ctx context.Context, arg AddGameNoteReactionParams) error {
	_, err := q.db.Exec(ctx, addGameNoteReaction,
		arg.GameNoteID,
		arg.UserID,
		arg.EmoteID,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const getGameNoteReactionsByGameNoteId = `-- name: GetGameNoteReactionsByGameNoteId :many
SELECT 
    gnr."emote_id",
    gnr."source",
    COUNT(*) as "count"
FROM "game_note_reactions" gnr
WHERE gnr."game_note_id" = $1
GROUP BY gnr."game_note_id", gnr."emote_id", gnr."source"
`

type GetGameNoteReactionsByGameNoteIdRow struct {
	EmoteID string         `json:"emote_id"`
	Source  ReactionSource `json:"source"`
	Count   int64          `json:"count"`
}

func (q *Queries) GetGameNoteReactionsByGameNoteId(ctx context.Context, gameNoteID uuid.UUID) ([]*GetGameNoteReactionsByGameNoteIdRow, error) {
	rows, err := q.db.Query(ctx, getGameNoteReactionsByGameNoteId, gameNoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGameNoteReactionsByGameNoteIdRow
	for rows.Next() {
		var i GetGameNoteReactionsByGameNoteIdRow
		if err := rows.Scan(&i.EmoteID, &i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameNoteReactionsByGameNoteIdAndUserId = `-- name: GetGameNoteReactionsByGameNoteIdAndUserId :many
SELECT 
    gnr."emote_id",
    gnr."source",
    COUNT(*) as "count",
    EXISTS (
        SELECT 1 
        FROM "game_note_reactions" r2 
        WHERE r2."game_note_id" = gnr."game_note_id" 
            AND r2."user_id" = $2 
            AND r2."emote_id" = gnr."emote_id"
            AND r2."source" = gnr."source"
    ) as "reacted_by_user"
FROM "game_note_reactions" gnr
WHERE gnr."game_note_id" = $1
GROUP BY gnr."game_note_id", gnr."emote_id", gnr."source"
`

type GetGameNoteReactionsByGameNoteIdAndUserIdParams struct {
	GameNoteID uuid.UUID `json:"game_note_id"`
	UserID     uuid.UUID `json:"user_id"`
}

type GetGameNoteReactionsByGameNoteIdAndUserIdRow struct {
	EmoteID       string         `json:"emote_id"`
	Source        ReactionSource `json:"source"`
	Count         int64          `json:"count"`
	ReactedByUser bool           `json:"reacted_by_user"`
}

func (q *Queries) GetGameNoteReactionsByGameNoteIdAndUserId(ctx context.Context, arg GetGameNoteReactionsByGameNoteIdAndUserIdParams) ([]*GetGameNoteReactionsByGameNoteIdAndUserIdRow, error) {
	rows, err := q.db.Query(ctx, getGameNoteReactionsByGameNoteIdAndUserId, arg.GameNoteID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetGameNoteReactionsByGameNoteIdAndUserIdRow
	for rows.Next() {
		var i GetGameNoteReactionsByGameNoteIdAndUserIdRow
		if err := rows.Scan(
			&i.EmoteID,
			&i.Source,
			&i.Count,
			&i.ReactedByUser,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGameNoteReaction = `-- name: RemoveGameNoteReaction :exec
DELETE FROM "game_note_reactions"
WHERE "game_note_id" = $1 
    AND "user_id" = $2 
    AND "emote_id" = $3
    AND "source" = $4
`

type RemoveGameNoteReactionParams struct {
	GameNoteID uuid.UUID      `json:"game_note_id"`
	UserID     uuid.UUID      `json:"user_id"`
	EmoteID    string         `json:"emote_id"`
	Source     ReactionSource `json:"source"`
}

func (q *Queries) RemoveGameNoteReaction(ctx context.Context, arg RemoveGameNoteReactionParams) error {
	_, err := q.db.Exec(ctx, removeGameNoteReaction,
		arg.GameNoteID,
		arg.UserID,
		arg.EmoteID,
		arg.Source,
	)
	return err
}
