// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_notes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPlayedGameNotesByUserId = `-- name: CountPlayedGameNotesByUserId :one
SELECT COUNT(*) AS "count"
FROM "game_notes"
WHERE "user_id" = $1
    AND "status" IN ('playing', 'finished', 'dropped')
GROUP BY "user_id"
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) CountPlayedGameNotesByUserId(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayedGameNotesByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findGameNoteById = `-- name: FindGameNoteById :one
SELECT id, created_at, created_by, updated_at, updated_by, user_id, game_id, name, link, release_date, rate, comment, initial_orderer_id, status, last_played_at, poster_key, poster_updated_at
FROM "game_notes"
WHERE "id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindGameNoteById(ctx context.Context, id uuid.UUID) (*GameNote, error) {
	row := q.db.QueryRow(ctx, findGameNoteById, id)
	var i GameNote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.GameID,
		&i.Name,
		&i.Link,
		&i.ReleaseDate,
		&i.Rate,
		&i.Comment,
		&i.InitialOrdererID,
		&i.Status,
		&i.LastPlayedAt,
		&i.PosterKey,
		&i.PosterUpdatedAt,
	)
	return &i, err
}

const findPaginatedGameNotesByUserId = `-- name: FindPaginatedGameNotesByUserId :many
SELECT 
    gn."id",
    gn."created_at",
    gn."name",
    gn."status",
    gn."rate",
    gn."comment",
    gn."release_date",
    o."username" AS "initial_orderer_username"
FROM "game_notes" gn
    JOIN "orderers" o ON gn."initial_orderer_id" = o."id"
WHERE gn."user_id" = $1
    AND gn."updated_at" < $2
ORDER BY gn."updated_at" DESC
LIMIT $3
`

type FindPaginatedGameNotesByUserIdParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

type FindPaginatedGameNotesByUserIdRow struct {
	ID                     uuid.UUID      `json:"id"`
	CreatedAt              time.Time      `json:"created_at"`
	Name                   string         `json:"name"`
	Status                 GameNoteStatus `json:"status"`
	Rate                   *int16         `json:"rate"`
	Comment                *string        `json:"comment"`
	ReleaseDate            *time.Time     `json:"release_date"`
	InitialOrdererUsername string         `json:"initial_orderer_username"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindPaginatedGameNotesByUserId(ctx context.Context, arg FindPaginatedGameNotesByUserIdParams) ([]*FindPaginatedGameNotesByUserIdRow, error) {
	rows, err := q.db.Query(ctx, findPaginatedGameNotesByUserId, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*FindPaginatedGameNotesByUserIdRow
	for rows.Next() {
		var i FindPaginatedGameNotesByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Status,
			&i.Rate,
			&i.Comment,
			&i.ReleaseDate,
			&i.InitialOrdererUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGameNote = `-- name: InsertGameNote :one
INSERT INTO "game_notes" (
    "created_by",
    "updated_by",
    "name",
    "link",
    "release_date",
    "game_id",
    "user_id",
    "rate",
    "comment",
    "initial_orderer_id",
    "status",
    "last_played_at",
    "poster_key"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, created_at, created_by, updated_at, updated_by, user_id, game_id, name, link, release_date, rate, comment, initial_orderer_id, status, last_played_at, poster_key, poster_updated_at
`

type InsertGameNoteParams struct {
	CreatedBy        uuid.UUID      `json:"created_by"`
	UpdatedBy        uuid.UUID      `json:"updated_by"`
	Name             string         `json:"name"`
	Link             *string        `json:"link"`
	ReleaseDate      *time.Time     `json:"release_date"`
	GameID           *uuid.UUID     `json:"game_id"`
	UserID           uuid.UUID      `json:"user_id"`
	Rate             *int16         `json:"rate"`
	Comment          *string        `json:"comment"`
	InitialOrdererID uuid.UUID      `json:"initial_orderer_id"`
	Status           GameNoteStatus `json:"status"`
	LastPlayedAt     *time.Time     `json:"last_played_at"`
	PosterKey        *string        `json:"poster_key"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertGameNote(ctx context.Context, arg InsertGameNoteParams) (*GameNote, error) {
	row := q.db.QueryRow(ctx, insertGameNote,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.Name,
		arg.Link,
		arg.ReleaseDate,
		arg.GameID,
		arg.UserID,
		arg.Rate,
		arg.Comment,
		arg.InitialOrdererID,
		arg.Status,
		arg.LastPlayedAt,
		arg.PosterKey,
	)
	var i GameNote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.GameID,
		&i.Name,
		&i.Link,
		&i.ReleaseDate,
		&i.Rate,
		&i.Comment,
		&i.InitialOrdererID,
		&i.Status,
		&i.LastPlayedAt,
		&i.PosterKey,
		&i.PosterUpdatedAt,
	)
	return &i, err
}
