// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_note_reactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addGameNoteReaction = `-- name: AddGameNoteReaction :exec
INSERT INTO "game_note_reactions" (
    "game_note_id",
    "user_id",
    "emote_id",
    "source",
    "created_by"
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::reaction_source,
    $5::uuid
)
`

type AddGameNoteReactionParams struct {
	GameNoteID uuid.UUID      `json:"game_note_id"`
	UserID     uuid.UUID      `json:"user_id"`
	EmoteID    string         `json:"emote_id"`
	Source     ReactionSource `json:"source"`
	CreatedBy  uuid.UUID      `json:"created_by"`
}

func (q *Queries) AddGameNoteReaction(ctx context.Context, arg AddGameNoteReactionParams) error {
	_, err := q.db.Exec(ctx, addGameNoteReaction,
		arg.GameNoteID,
		arg.UserID,
		arg.EmoteID,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const countGameNoteReactionsByGameNoteIdAndUserId = `-- name: CountGameNoteReactionsByGameNoteIdAndUserId :one
SELECT COUNT(*) FROM "game_note_reactions"
WHERE "game_note_id" = $1::uuid
    AND "user_id" = $2::uuid
`

type CountGameNoteReactionsByGameNoteIdAndUserIdParams struct {
	GameNoteID uuid.UUID `json:"game_note_id"`
	UserID     uuid.UUID `json:"user_id"`
}

func (q *Queries) CountGameNoteReactionsByGameNoteIdAndUserId(ctx context.Context, arg CountGameNoteReactionsByGameNoteIdAndUserIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGameNoteReactionsByGameNoteIdAndUserId, arg.GameNoteID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGameNoteReactionsByGameNoteIdInAndUserId = `-- name: GetGameNoteReactionsByGameNoteIdInAndUserId :many
SELECT 
    gnr."game_note_id",
    gnr."emote_id",
    gnr."source",
    COUNT(DISTINCT gnr."user_id") AS "count",
    COALESCE(
        (
            SELECT 1 
            FROM "game_note_reactions" r2 
            WHERE r2."game_note_id" = gnr."game_note_id" 
                AND r2."user_id" = $1::uuid
                AND r2."emote_id" = gnr."emote_id"
                AND r2."source" = gnr."source"
        ), 0) AS "reacted_by_user"
FROM "game_note_reactions" gnr
WHERE gnr."game_note_id" = ANY($2::uuid[])
GROUP BY gnr."game_note_id", gnr."emote_id", gnr."source"
ORDER BY "count" DESC
`

type GetGameNoteReactionsByGameNoteIdInAndUserIdParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	GameNoteIds []uuid.UUID `json:"game_note_ids"`
}

type GetGameNoteReactionsByGameNoteIdInAndUserIdRow struct {
	GameNoteID    uuid.UUID      `json:"game_note_id"`
	EmoteID       string         `json:"emote_id"`
	Source        ReactionSource `json:"source"`
	Count         int64          `json:"count"`
	ReactedByUser *int32         `json:"reacted_by_user"`
}

func (q *Queries) GetGameNoteReactionsByGameNoteIdInAndUserId(ctx context.Context, arg GetGameNoteReactionsByGameNoteIdInAndUserIdParams) ([]*GetGameNoteReactionsByGameNoteIdInAndUserIdRow, error) {
	rows, err := q.db.Query(ctx, getGameNoteReactionsByGameNoteIdInAndUserId, arg.UserID, arg.GameNoteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetGameNoteReactionsByGameNoteIdInAndUserIdRow{}
	for rows.Next() {
		var i GetGameNoteReactionsByGameNoteIdInAndUserIdRow
		if err := rows.Scan(
			&i.GameNoteID,
			&i.EmoteID,
			&i.Source,
			&i.Count,
			&i.ReactedByUser,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGameNoteReaction = `-- name: RemoveGameNoteReaction :exec
DELETE FROM "game_note_reactions"
WHERE "game_note_id" = $1::uuid
    AND "user_id" = $2::uuid
    AND "emote_id" = $3::text
    AND "source" = $4::reaction_source
`

type RemoveGameNoteReactionParams struct {
	GameNoteID uuid.UUID      `json:"game_note_id"`
	UserID     uuid.UUID      `json:"user_id"`
	EmoteID    string         `json:"emote_id"`
	Source     ReactionSource `json:"source"`
}

func (q *Queries) RemoveGameNoteReaction(ctx context.Context, arg RemoveGameNoteReactionParams) error {
	_, err := q.db.Exec(ctx, removeGameNoteReaction,
		arg.GameNoteID,
		arg.UserID,
		arg.EmoteID,
		arg.Source,
	)
	return err
}
