// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_notes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countGameNotesByUserId = `-- name: CountGameNotesByUserId :one
SELECT COUNT(*) AS "total"
FROM "game_notes"
WHERE "user_id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) CountGameNotesByUserId(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGameNotesByUserId, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const findGameNoteById = `-- name: FindGameNoteById :one
SELECT id, created_at, created_by, updated_at, updated_by, user_id, game_id, name, link, release_date, rate, comment, ordered, status, last_played_at
FROM "game_notes"
WHERE "id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindGameNoteById(ctx context.Context, id uuid.UUID) (*GameNote, error) {
	row := q.db.QueryRow(ctx, findGameNoteById, id)
	var i GameNote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.GameID,
		&i.Name,
		&i.Link,
		&i.ReleaseDate,
		&i.Rate,
		&i.Comment,
		&i.Ordered,
		&i.Status,
		&i.LastPlayedAt,
	)
	return &i, err
}

const findPaginatedGameNotesByUserId = `-- name: FindPaginatedGameNotesByUserId :many
SELECT id, created_at, created_by, updated_at, updated_by, user_id, game_id, name, link, release_date, rate, comment, ordered, status, last_played_at 
FROM "game_notes" 
WHERE "user_id" = $1
    AND "updated_at" < $2
ORDER BY "updated_at" DESC
LIMIT $3
`

type FindPaginatedGameNotesByUserIdParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindPaginatedGameNotesByUserId(ctx context.Context, arg FindPaginatedGameNotesByUserIdParams) ([]*GameNote, error) {
	rows, err := q.db.Query(ctx, findPaginatedGameNotesByUserId, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GameNote
	for rows.Next() {
		var i GameNote
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.UserID,
			&i.GameID,
			&i.Name,
			&i.Link,
			&i.ReleaseDate,
			&i.Rate,
			&i.Comment,
			&i.Ordered,
			&i.Status,
			&i.LastPlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGameNote = `-- name: InsertGameNote :one
INSERT INTO "game_notes" (
    "created_by",
    "updated_by",
    "name",
    "link",
    "release_date",
    "game_id",
    "user_id",
    "rate",
    "comment",
    "ordered",
    "status",
    "last_played_at"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, created_at, created_by, updated_at, updated_by, user_id, game_id, name, link, release_date, rate, comment, ordered, status, last_played_at
`

type InsertGameNoteParams struct {
	CreatedBy    uuid.UUID      `json:"created_by"`
	UpdatedBy    uuid.UUID      `json:"updated_by"`
	Name         string         `json:"name"`
	Link         *string        `json:"link"`
	ReleaseDate  *time.Time     `json:"release_date"`
	GameID       *uuid.UUID     `json:"game_id"`
	UserID       uuid.UUID      `json:"user_id"`
	Rate         *int16         `json:"rate"`
	Comment      *string        `json:"comment"`
	Ordered      bool           `json:"ordered"`
	Status       GameNoteStatus `json:"status"`
	LastPlayedAt *time.Time     `json:"last_played_at"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertGameNote(ctx context.Context, arg InsertGameNoteParams) (*GameNote, error) {
	row := q.db.QueryRow(ctx, insertGameNote,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.Name,
		arg.Link,
		arg.ReleaseDate,
		arg.GameID,
		arg.UserID,
		arg.Rate,
		arg.Comment,
		arg.Ordered,
		arg.Status,
		arg.LastPlayedAt,
	)
	var i GameNote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.GameID,
		&i.Name,
		&i.Link,
		&i.ReleaseDate,
		&i.Rate,
		&i.Comment,
		&i.Ordered,
		&i.Status,
		&i.LastPlayedAt,
	)
	return &i, err
}
