// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_notes.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countPlayedGameNotesByUserID = `-- name: CountPlayedGameNotesByUserID :one
SELECT COUNT(*) AS count
FROM game_notes
WHERE user_id = $1::uuid
    AND status IN ('playing', 'finished', 'dropped', 'paused')
GROUP BY user_id
`

func (q *Queries) CountPlayedGameNotesByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayedGameNotesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGameNoteByID = `-- name: DeleteGameNoteByID :exec
DELETE FROM game_notes
WHERE id = $1::uuid
`

func (q *Queries) DeleteGameNoteByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGameNoteByID, id)
	return err
}

const findDetailedGameNoteByID = `-- name: FindDetailedGameNoteByID :one
SELECT gn.id, gn.created_at, gn.created_by, gn.updated_at, gn.updated_by, gn.user_id, gn.content_id, gn.rate, gn.comment, gn.initial_orderer_id, gn.status, gn.last_played_at,
    COALESCE(gl.title, 'Untitled Game') AS title,
    g.cover_key,
    g.cover_key_type,
    g.source_url,
    g.source_type,
    g.websites,
    g.release_date
FROM game_notes gn
    LEFT JOIN games g ON gn.content_id = g.id
    LEFT JOIN game_localizations gl ON g.id = gl.content_id
    AND gl.lang = $1::text
WHERE gn.id = $2::uuid
`

type FindDetailedGameNoteByIDParams struct {
	Locale string    `json:"locale"`
	ID     uuid.UUID `json:"id"`
}

type FindDetailedGameNoteByIDRow struct {
	ID               uuid.UUID         `json:"id"`
	CreatedAt        time.Time         `json:"created_at"`
	CreatedBy        uuid.UUID         `json:"created_by"`
	UpdatedAt        time.Time         `json:"updated_at"`
	UpdatedBy        uuid.UUID         `json:"updated_by"`
	UserID           uuid.UUID         `json:"user_id"`
	ContentID        uuid.UUID         `json:"content_id"`
	Rate             *int16            `json:"rate"`
	Comment          *string           `json:"comment"`
	InitialOrdererID uuid.UUID         `json:"initial_orderer_id"`
	Status           GameNoteStatus    `json:"status"`
	LastPlayedAt     *time.Time        `json:"last_played_at"`
	Title            string            `json:"title"`
	CoverKey         *string           `json:"cover_key"`
	CoverKeyType     NullImageKeyType  `json:"cover_key_type"`
	SourceUrl        *string           `json:"source_url"`
	SourceType       NullContentSource `json:"source_type"`
	Websites         *json.RawMessage  `json:"websites"`
	ReleaseDate      *time.Time        `json:"release_date"`
}

func (q *Queries) FindDetailedGameNoteByID(ctx context.Context, arg FindDetailedGameNoteByIDParams) (*FindDetailedGameNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, findDetailedGameNoteByID, arg.Locale, arg.ID)
	var i FindDetailedGameNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.ContentID,
		&i.Rate,
		&i.Comment,
		&i.InitialOrdererID,
		&i.Status,
		&i.LastPlayedAt,
		&i.Title,
		&i.CoverKey,
		&i.CoverKeyType,
		&i.SourceUrl,
		&i.SourceType,
		&i.Websites,
		&i.ReleaseDate,
	)
	return &i, err
}

const findGameNoteByContentID = `-- name: FindGameNoteByContentID :one
SELECT id, created_at, created_by, updated_at, updated_by, user_id, content_id, rate, comment, initial_orderer_id, status, last_played_at
FROM game_notes
WHERE content_id = $1::uuid
    AND user_id = $2::uuid
`

type FindGameNoteByContentIDParams struct {
	ContentID uuid.UUID `json:"content_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) FindGameNoteByContentID(ctx context.Context, arg FindGameNoteByContentIDParams) (*GameNote, error) {
	row := q.db.QueryRow(ctx, findGameNoteByContentID, arg.ContentID, arg.UserID)
	var i GameNote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.ContentID,
		&i.Rate,
		&i.Comment,
		&i.InitialOrdererID,
		&i.Status,
		&i.LastPlayedAt,
	)
	return &i, err
}

const findGameNoteByID = `-- name: FindGameNoteByID :one
SELECT id, created_at, created_by, updated_at, updated_by, user_id, content_id, rate, comment, initial_orderer_id, status, last_played_at
FROM game_notes
WHERE id = $1::uuid
`

func (q *Queries) FindGameNoteByID(ctx context.Context, id uuid.UUID) (*GameNote, error) {
	row := q.db.QueryRow(ctx, findGameNoteByID, id)
	var i GameNote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.ContentID,
		&i.Rate,
		&i.Comment,
		&i.InitialOrdererID,
		&i.Status,
		&i.LastPlayedAt,
	)
	return &i, err
}

const findGameNoteContentIDsByUserID = `-- name: FindGameNoteContentIDsByUserID :many
SELECT DISTINCT content_id
FROM game_notes
WHERE user_id = $1::uuid
`

func (q *Queries) FindGameNoteContentIDsByUserID(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findGameNoteContentIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var content_id uuid.UUID
		if err := rows.Scan(&content_id); err != nil {
			return nil, err
		}
		items = append(items, content_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLocalizedGameNoteByID = `-- name: FindLocalizedGameNoteByID :one
SELECT gn.id, gn.created_at, gn.created_by, gn.updated_at, gn.updated_by, gn.user_id, gn.content_id, gn.rate, gn.comment, gn.initial_orderer_id, gn.status, gn.last_played_at,
    COALESCE(gl.title, 'Untitled Game') AS title
FROM game_notes gn
    LEFT JOIN game_localizations gl ON gn.content_id = gl.content_id
    AND gl.lang = $1::text
WHERE gn.id = $2::uuid
`

type FindLocalizedGameNoteByIDParams struct {
	Locale string    `json:"locale"`
	ID     uuid.UUID `json:"id"`
}

type FindLocalizedGameNoteByIDRow struct {
	ID               uuid.UUID      `json:"id"`
	CreatedAt        time.Time      `json:"created_at"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        uuid.UUID      `json:"updated_by"`
	UserID           uuid.UUID      `json:"user_id"`
	ContentID        uuid.UUID      `json:"content_id"`
	Rate             *int16         `json:"rate"`
	Comment          *string        `json:"comment"`
	InitialOrdererID uuid.UUID      `json:"initial_orderer_id"`
	Status           GameNoteStatus `json:"status"`
	LastPlayedAt     *time.Time     `json:"last_played_at"`
	Title            string         `json:"title"`
}

func (q *Queries) FindLocalizedGameNoteByID(ctx context.Context, arg FindLocalizedGameNoteByIDParams) (*FindLocalizedGameNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, findLocalizedGameNoteByID, arg.Locale, arg.ID)
	var i FindLocalizedGameNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.ContentID,
		&i.Rate,
		&i.Comment,
		&i.InitialOrdererID,
		&i.Status,
		&i.LastPlayedAt,
		&i.Title,
	)
	return &i, err
}

const findPaginatedGameNotesByUserID = `-- name: FindPaginatedGameNotesByUserID :many
SELECT gn.id,
    gn.created_at,
    gn.content_id,
    gn.status,
    gn.rate,
    gn.comment,
    gn.last_played_at,
    o.display_name AS initial_orderer_display_name,
    COALESCE(order_counts.count, 0) AS orderer_count
FROM game_notes gn
    INNER JOIN orderers o ON gn.initial_orderer_id = o.id
    LEFT JOIN (
        SELECT game_note_id,
            COUNT(*) as count
        FROM game_note_orders
        GROUP BY game_note_id
    ) order_counts ON gn.id = order_counts.game_note_id
WHERE gn.user_id = $1::uuid
    AND gn.updated_at < $2::timestamptz
ORDER BY gn.updated_at DESC
LIMIT $3::int
`

type FindPaginatedGameNotesByUserIDParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

type FindPaginatedGameNotesByUserIDRow struct {
	ID                        uuid.UUID      `json:"id"`
	CreatedAt                 time.Time      `json:"created_at"`
	ContentID                 uuid.UUID      `json:"content_id"`
	Status                    GameNoteStatus `json:"status"`
	Rate                      *int16         `json:"rate"`
	Comment                   *string        `json:"comment"`
	LastPlayedAt              *time.Time     `json:"last_played_at"`
	InitialOrdererDisplayName string         `json:"initial_orderer_display_name"`
	OrdererCount              int64          `json:"orderer_count"`
}

func (q *Queries) FindPaginatedGameNotesByUserID(ctx context.Context, arg FindPaginatedGameNotesByUserIDParams) ([]*FindPaginatedGameNotesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, findPaginatedGameNotesByUserID, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindPaginatedGameNotesByUserIDRow{}
	for rows.Next() {
		var i FindPaginatedGameNotesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ContentID,
			&i.Status,
			&i.Rate,
			&i.Comment,
			&i.LastPlayedAt,
			&i.InitialOrdererDisplayName,
			&i.OrdererCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGameNote = `-- name: InsertGameNote :one
INSERT INTO game_notes (
        created_by,
        updated_by,
        content_id,
        user_id,
        rate,
        comment,
        initial_orderer_id,
        status,
        last_played_at
    )
VALUES (
        $1::uuid,
        $1::uuid,
        $2::uuid,
        $3::uuid,
        $4::smallint,
        $5::text,
        $6::uuid,
        $7::game_note_status,
        $8::timestamptz
    )
RETURNING id, created_at, created_by, updated_at, updated_by, user_id, content_id, rate, comment, initial_orderer_id, status, last_played_at
`

type InsertGameNoteParams struct {
	CreatedBy        uuid.UUID      `json:"created_by"`
	ContentID        uuid.UUID      `json:"content_id"`
	UserID           uuid.UUID      `json:"user_id"`
	Rate             *int16         `json:"rate"`
	Comment          *string        `json:"comment"`
	InitialOrdererID uuid.UUID      `json:"initial_orderer_id"`
	Status           GameNoteStatus `json:"status"`
	LastPlayedAt     *time.Time     `json:"last_played_at"`
}

func (q *Queries) InsertGameNote(ctx context.Context, arg InsertGameNoteParams) (*GameNote, error) {
	row := q.db.QueryRow(ctx, insertGameNote,
		arg.CreatedBy,
		arg.ContentID,
		arg.UserID,
		arg.Rate,
		arg.Comment,
		arg.InitialOrdererID,
		arg.Status,
		arg.LastPlayedAt,
	)
	var i GameNote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.ContentID,
		&i.Rate,
		&i.Comment,
		&i.InitialOrdererID,
		&i.Status,
		&i.LastPlayedAt,
	)
	return &i, err
}

const updateGameNoteByID = `-- name: UpdateGameNoteByID :exec
UPDATE game_notes
SET updated_by = $1::uuid,
    updated_at = now(),
    rate = $2::smallint,
    comment = $3::text,
    status = $4::game_note_status,
    last_played_at = $5::timestamptz
WHERE id = $6::uuid
`

type UpdateGameNoteByIDParams struct {
	UpdatedBy    uuid.UUID      `json:"updated_by"`
	Rate         *int16         `json:"rate"`
	Comment      *string        `json:"comment"`
	Status       GameNoteStatus `json:"status"`
	LastPlayedAt *time.Time     `json:"last_played_at"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateGameNoteByID(ctx context.Context, arg UpdateGameNoteByIDParams) error {
	_, err := q.db.Exec(ctx, updateGameNoteByID,
		arg.UpdatedBy,
		arg.Rate,
		arg.Comment,
		arg.Status,
		arg.LastPlayedAt,
		arg.ID,
	)
	return err
}
