// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: igdb_sync_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeIGDBSync = `-- name: CompleteIGDBSync :exec
UPDATE igdb_sync_logs
SET status = 'completed',
    completed_at = now(),
    games_processed = $1::bigint
WHERE id = $2
`

type CompleteIGDBSyncParams struct {
	GamesProcessed int64     `json:"games_processed"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) CompleteIGDBSync(ctx context.Context, arg CompleteIGDBSyncParams) error {
	_, err := q.db.Exec(ctx, completeIGDBSync, arg.GamesProcessed, arg.ID)
	return err
}

const completeIGDBSyncWithError = `-- name: CompleteIGDBSyncWithError :exec
UPDATE igdb_sync_logs
SET status = 'failed',
    completed_at = now(),
    error_message = $1::text
WHERE id = $2
`

type CompleteIGDBSyncWithErrorParams struct {
	ErrorMessage string    `json:"error_message"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) CompleteIGDBSyncWithError(ctx context.Context, arg CompleteIGDBSyncWithErrorParams) error {
	_, err := q.db.Exec(ctx, completeIGDBSyncWithError, arg.ErrorMessage, arg.ID)
	return err
}

const createIGDBSync = `-- name: CreateIGDBSync :one
INSERT INTO igdb_sync_logs (sync_type, started_at, status)
VALUES (
        $1::igdb_sync_type,
        now(),
        'pending'
    )
RETURNING id, sync_type, status, started_at, games_processed, completed_at, error_message
`

func (q *Queries) CreateIGDBSync(ctx context.Context, syncType IgdbSyncType) (*IgdbSyncLog, error) {
	row := q.db.QueryRow(ctx, createIGDBSync, syncType)
	var i IgdbSyncLog
	err := row.Scan(
		&i.ID,
		&i.SyncType,
		&i.Status,
		&i.StartedAt,
		&i.GamesProcessed,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return &i, err
}

const getLastSuccessfulSync = `-- name: GetLastSuccessfulSync :one
SELECT id, sync_type, status, started_at, games_processed, completed_at, error_message
FROM igdb_sync_logs
WHERE sync_type = $1::igdb_sync_type
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulSync(ctx context.Context, syncType IgdbSyncType) (*IgdbSyncLog, error) {
	row := q.db.QueryRow(ctx, getLastSuccessfulSync, syncType)
	var i IgdbSyncLog
	err := row.Scan(
		&i.ID,
		&i.SyncType,
		&i.Status,
		&i.StartedAt,
		&i.GamesProcessed,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return &i, err
}

const startIGDBSync = `-- name: StartIGDBSync :exec
UPDATE igdb_sync_logs
SET status = 'in_progress'
WHERE id = $1
`

func (q *Queries) StartIGDBSync(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startIGDBSync, id)
	return err
}
