// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: migrations.sql

package db

import (
	"context"
)

const findElasticsearchMigrationByName = `-- name: FindElasticsearchMigrationByName :one
SELECT id, name, created_at FROM "es_migration_logs" WHERE name = $1
`

func (q *Queries) FindElasticsearchMigrationByName(ctx context.Context, name string) (*EsMigrationLog, error) {
	row := q.db.QueryRow(ctx, findElasticsearchMigrationByName, name)
	var i EsMigrationLog
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return &i, err
}

const insertElasticsearchMigration = `-- name: InsertElasticsearchMigration :exec
INSERT INTO "es_migration_logs" (name, created_at) VALUES ($1, now())
`

func (q *Queries) InsertElasticsearchMigration(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertElasticsearchMigration, name)
	return err
}
