// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: moderators.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteModeratorByUserIDAndModeratorID = `-- name: DeleteModeratorByUserIDAndModeratorID :exec
UPDATE moderators
SET deleted_at = now(),
    deleted_by = $1::uuid
WHERE user_id = $2::uuid
    AND moderator_id = $3::uuid
    AND deleted_at IS NULL
`

type DeleteModeratorByUserIDAndModeratorIDParams struct {
	DeletedBy   uuid.UUID `json:"deleted_by"`
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
}

func (q *Queries) DeleteModeratorByUserIDAndModeratorID(ctx context.Context, arg DeleteModeratorByUserIDAndModeratorIDParams) error {
	_, err := q.db.Exec(ctx, deleteModeratorByUserIDAndModeratorID, arg.DeletedBy, arg.UserID, arg.ModeratorID)
	return err
}

const findModeratorByUserIDAndModeratorID = `-- name: FindModeratorByUserIDAndModeratorID :one
SELECT id, created_at, created_by, deleted_at, deleted_by, user_id, moderator_id
FROM moderators
WHERE user_id = $1::uuid
    AND moderator_id = $2::uuid
`

type FindModeratorByUserIDAndModeratorIDParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
}

func (q *Queries) FindModeratorByUserIDAndModeratorID(ctx context.Context, arg FindModeratorByUserIDAndModeratorIDParams) (*Moderator, error) {
	row := q.db.QueryRow(ctx, findModeratorByUserIDAndModeratorID, arg.UserID, arg.ModeratorID)
	var i Moderator
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.UserID,
		&i.ModeratorID,
	)
	return &i, err
}

const findModeratorByUserIDAndModeratorIDAndNotDeleted = `-- name: FindModeratorByUserIDAndModeratorIDAndNotDeleted :one
SELECT id, created_at, created_by, deleted_at, deleted_by, user_id, moderator_id
FROM moderators
WHERE user_id = $1::uuid
    AND moderator_id = $2::uuid
    AND deleted_at IS NULL
`

type FindModeratorByUserIDAndModeratorIDAndNotDeletedParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
}

func (q *Queries) FindModeratorByUserIDAndModeratorIDAndNotDeleted(ctx context.Context, arg FindModeratorByUserIDAndModeratorIDAndNotDeletedParams) (*Moderator, error) {
	row := q.db.QueryRow(ctx, findModeratorByUserIDAndModeratorIDAndNotDeleted, arg.UserID, arg.ModeratorID)
	var i Moderator
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.UserID,
		&i.ModeratorID,
	)
	return &i, err
}

const findModeratorProfileByUserIDAndModeratorID = `-- name: FindModeratorProfileByUserIDAndModeratorID :one
SELECT p.user_id,
    p.display_name,
    p.username,
    m.created_at AS added_at,
    pa.avatar_url
FROM profiles p
    INNER JOIN moderators m ON p.user_id = m.moderator_id
    AND m.deleted_at IS NULL
    INNER JOIN profile_avatars pa ON p.user_id = pa.user_id
WHERE m.user_id = $1::uuid
    AND m.moderator_id = $2::uuid
`

type FindModeratorProfileByUserIDAndModeratorIDParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
}

type FindModeratorProfileByUserIDAndModeratorIDRow struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Username    string    `json:"username"`
	AddedAt     time.Time `json:"added_at"`
	AvatarUrl   *string   `json:"avatar_url"`
}

func (q *Queries) FindModeratorProfileByUserIDAndModeratorID(ctx context.Context, arg FindModeratorProfileByUserIDAndModeratorIDParams) (*FindModeratorProfileByUserIDAndModeratorIDRow, error) {
	row := q.db.QueryRow(ctx, findModeratorProfileByUserIDAndModeratorID, arg.UserID, arg.ModeratorID)
	var i FindModeratorProfileByUserIDAndModeratorIDRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.AddedAt,
		&i.AvatarUrl,
	)
	return &i, err
}

const findModeratorProfilesByUserID = `-- name: FindModeratorProfilesByUserID :many
SELECT p.user_id,
    p.display_name,
    p.username,
    m.created_at AS added_at,
    pa.avatar_url
FROM profiles p
    INNER JOIN moderators m ON p.user_id = m.moderator_id
    AND m.deleted_at IS NULL
    INNER JOIN profile_avatars pa ON p.user_id = pa.user_id
WHERE m.user_id = $1::uuid
ORDER BY m.created_at DESC
`

type FindModeratorProfilesByUserIDRow struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Username    string    `json:"username"`
	AddedAt     time.Time `json:"added_at"`
	AvatarUrl   *string   `json:"avatar_url"`
}

func (q *Queries) FindModeratorProfilesByUserID(ctx context.Context, userID uuid.UUID) ([]*FindModeratorProfilesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, findModeratorProfilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindModeratorProfilesByUserIDRow{}
	for rows.Next() {
		var i FindModeratorProfilesByUserIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Username,
			&i.AddedAt,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findModeratorsByUserID = `-- name: FindModeratorsByUserID :many
SELECT id, created_at, created_by, deleted_at, deleted_by, user_id, moderator_id
FROM moderators
WHERE user_id = $1::uuid
    AND deleted_at IS NULL
`

func (q *Queries) FindModeratorsByUserID(ctx context.Context, userID uuid.UUID) ([]*Moderator, error) {
	rows, err := q.db.Query(ctx, findModeratorsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Moderator{}
	for rows.Next() {
		var i Moderator
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.UserID,
			&i.ModeratorID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProfilesByModeratorID = `-- name: FindProfilesByModeratorID :many
SELECT p.user_id,
    p.display_name,
    p.username,
    m.created_at
FROM profiles p
    INNER JOIN moderators m ON p.user_id = m.user_id
    AND m.deleted_at IS NULL
WHERE m.moderator_id = $1::uuid
ORDER BY m.created_at DESC
`

type FindProfilesByModeratorIDRow struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Username    string    `json:"username"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) FindProfilesByModeratorID(ctx context.Context, moderatorID uuid.UUID) ([]*FindProfilesByModeratorIDRow, error) {
	rows, err := q.db.Query(ctx, findProfilesByModeratorID, moderatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindProfilesByModeratorIDRow{}
	for rows.Next() {
		var i FindProfilesByModeratorIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertModerator = `-- name: InsertModerator :one
INSERT INTO moderators (user_id, moderator_id, created_by)
VALUES (
        $1::uuid,
        $2::uuid,
        $3::uuid
    )
RETURNING id, created_at, created_by, deleted_at, deleted_by, user_id, moderator_id
`

type InsertModeratorParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

func (q *Queries) InsertModerator(ctx context.Context, arg InsertModeratorParams) (*Moderator, error) {
	row := q.db.QueryRow(ctx, insertModerator, arg.UserID, arg.ModeratorID, arg.CreatedBy)
	var i Moderator
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.UserID,
		&i.ModeratorID,
	)
	return &i, err
}

const revertModeratorByUserIDAndModeratorID = `-- name: RevertModeratorByUserIDAndModeratorID :exec
UPDATE moderators
SET deleted_at = NULL,
    deleted_by = NULL
WHERE user_id = $1::uuid
    AND moderator_id = $2::uuid
`

type RevertModeratorByUserIDAndModeratorIDParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ModeratorID uuid.UUID `json:"moderator_id"`
}

func (q *Queries) RevertModeratorByUserIDAndModeratorID(ctx context.Context, arg RevertModeratorByUserIDAndModeratorIDParams) error {
	_, err := q.db.Exec(ctx, revertModeratorByUserIDAndModeratorID, arg.UserID, arg.ModeratorID)
	return err
}
