// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ContentCategory string

const (
	ContentCategoryGames  ContentCategory = "games"
	ContentCategoryMovies ContentCategory = "movies"
	ContentCategoryVideo  ContentCategory = "video"
	ContentCategoryAnime  ContentCategory = "anime"
	ContentCategorySeries ContentCategory = "series"
	ContentCategoryCustom ContentCategory = "custom"
	ContentCategoryAny    ContentCategory = "any"
)

func (e *ContentCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentCategory(s)
	case string:
		*e = ContentCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentCategory: %T", src)
	}
	return nil
}

type NullContentCategory struct {
	ContentCategory ContentCategory `json:"content_category"`
	Valid           bool            `json:"valid"` // Valid is true if ContentCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ContentCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentCategory), nil
}

type ContentSource string

const (
	ContentSourceIgdb ContentSource = "igdb"
	ContentSourceTmdb ContentSource = "tmdb"
)

func (e *ContentSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentSource(s)
	case string:
		*e = ContentSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentSource: %T", src)
	}
	return nil
}

type NullContentSource struct {
	ContentSource ContentSource `json:"content_source"`
	Valid         bool          `json:"valid"` // Valid is true if ContentSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentSource) Scan(value interface{}) error {
	if value == nil {
		ns.ContentSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentSource), nil
}

type GameNoteStatus string

const (
	GameNoteStatusPlanned  GameNoteStatus = "planned"
	GameNoteStatusPlaying  GameNoteStatus = "playing"
	GameNoteStatusPaused   GameNoteStatus = "paused"
	GameNoteStatusDropped  GameNoteStatus = "dropped"
	GameNoteStatusFinished GameNoteStatus = "finished"
	GameNoteStatusSkipped  GameNoteStatus = "skipped"
)

func (e *GameNoteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameNoteStatus(s)
	case string:
		*e = GameNoteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GameNoteStatus: %T", src)
	}
	return nil
}

type NullGameNoteStatus struct {
	GameNoteStatus GameNoteStatus `json:"game_note_status"`
	Valid          bool           `json:"valid"` // Valid is true if GameNoteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameNoteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GameNoteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameNoteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameNoteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameNoteStatus), nil
}

type IgdbSyncStatus string

const (
	IgdbSyncStatusPending    IgdbSyncStatus = "pending"
	IgdbSyncStatusInProgress IgdbSyncStatus = "in_progress"
	IgdbSyncStatusCompleted  IgdbSyncStatus = "completed"
	IgdbSyncStatusFailed     IgdbSyncStatus = "failed"
)

func (e *IgdbSyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IgdbSyncStatus(s)
	case string:
		*e = IgdbSyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IgdbSyncStatus: %T", src)
	}
	return nil
}

type NullIgdbSyncStatus struct {
	IgdbSyncStatus IgdbSyncStatus `json:"igdb_sync_status"`
	Valid          bool           `json:"valid"` // Valid is true if IgdbSyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIgdbSyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IgdbSyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IgdbSyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIgdbSyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IgdbSyncStatus), nil
}

type IgdbSyncType string

const (
	IgdbSyncTypeFull        IgdbSyncType = "full"
	IgdbSyncTypeIncremental IgdbSyncType = "incremental"
)

func (e *IgdbSyncType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IgdbSyncType(s)
	case string:
		*e = IgdbSyncType(s)
	default:
		return fmt.Errorf("unsupported scan type for IgdbSyncType: %T", src)
	}
	return nil
}

type NullIgdbSyncType struct {
	IgdbSyncType IgdbSyncType `json:"igdb_sync_type"`
	Valid        bool         `json:"valid"` // Valid is true if IgdbSyncType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIgdbSyncType) Scan(value interface{}) error {
	if value == nil {
		ns.IgdbSyncType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IgdbSyncType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIgdbSyncType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IgdbSyncType), nil
}

type ImageKeyType string

const (
	ImageKeyTypeIgdb   ImageKeyType = "igdb"
	ImageKeyTypeTmdb   ImageKeyType = "tmdb"
	ImageKeyTypeCustom ImageKeyType = "custom"
)

func (e *ImageKeyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageKeyType(s)
	case string:
		*e = ImageKeyType(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageKeyType: %T", src)
	}
	return nil
}

type NullImageKeyType struct {
	ImageKeyType ImageKeyType `json:"image_key_type"`
	Valid        bool         `json:"valid"` // Valid is true if ImageKeyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImageKeyType) Scan(value interface{}) error {
	if value == nil {
		ns.ImageKeyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImageKeyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImageKeyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImageKeyType), nil
}

type Locale string

const (
	LocaleEn Locale = "en"
	LocaleRu Locale = "ru"
	LocaleDe Locale = "de"
	LocaleEs Locale = "es"
)

func (e *Locale) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Locale(s)
	case string:
		*e = Locale(s)
	default:
		return fmt.Errorf("unsupported scan type for Locale: %T", src)
	}
	return nil
}

type NullLocale struct {
	Locale Locale `json:"locale"`
	Valid  bool   `json:"valid"` // Valid is true if Locale is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocale) Scan(value interface{}) error {
	if value == nil {
		ns.Locale, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Locale.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocale) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Locale), nil
}

type MovieNoteStatus string

const (
	MovieNoteStatusPlanned MovieNoteStatus = "planned"
	MovieNoteStatusDropped MovieNoteStatus = "dropped"
	MovieNoteStatusWatched MovieNoteStatus = "watched"
	MovieNoteStatusSkipped MovieNoteStatus = "skipped"
)

func (e *MovieNoteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MovieNoteStatus(s)
	case string:
		*e = MovieNoteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MovieNoteStatus: %T", src)
	}
	return nil
}

type NullMovieNoteStatus struct {
	MovieNoteStatus MovieNoteStatus `json:"movie_note_status"`
	Valid           bool            `json:"valid"` // Valid is true if MovieNoteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMovieNoteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MovieNoteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MovieNoteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMovieNoteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MovieNoteStatus), nil
}

type OrderStatus string

const (
	OrderStatusPending  OrderStatus = "pending"
	OrderStatusApproved OrderStatus = "approved"
	OrderStatusRejected OrderStatus = "rejected"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type ReactionSource string

const (
	ReactionSourceUnicodeEmoji ReactionSource = "unicode_emoji"
	ReactionSource7tv          ReactionSource = "7tv"
	ReactionSourceCustom       ReactionSource = "custom"
)

func (e *ReactionSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReactionSource(s)
	case string:
		*e = ReactionSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ReactionSource: %T", src)
	}
	return nil
}

type NullReactionSource struct {
	ReactionSource ReactionSource `json:"reaction_source"`
	Valid          bool           `json:"valid"` // Valid is true if ReactionSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReactionSource) Scan(value interface{}) error {
	if value == nil {
		ns.ReactionSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReactionSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReactionSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReactionSource), nil
}

type Collection struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	CreatedBy uuid.UUID `json:"created_by"`
	UpdatedAt time.Time `json:"updated_at"`
	UpdatedBy uuid.UUID `json:"updated_by"`
	Name      string    `json:"name"`
	UserID    uuid.UUID `json:"user_id"`
}

type CollectionItem struct {
	ID           uuid.UUID       `json:"id"`
	CollectionID uuid.UUID       `json:"collection_id"`
	NoteID       uuid.UUID       `json:"note_id"`
	ContentID    uuid.UUID       `json:"content_id"`
	Category     ContentCategory `json:"category"`
	CreatedAt    time.Time       `json:"created_at"`
	CreatedBy    uuid.UUID       `json:"created_by"`
}

type EsMigrationLog struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Follower struct {
	UserID     uuid.UUID `json:"user_id"`
	FollowerID uuid.UUID `json:"follower_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Game struct {
	ID           uuid.UUID        `json:"id"`
	ExternalID   int64            `json:"external_id"`
	ReleaseDate  *time.Time       `json:"release_date"`
	Websites     []byte           `json:"websites"`
	CoverKey     *string          `json:"cover_key"`
	CoverKeyType NullImageKeyType `json:"cover_key_type"`
	SourceUrl    *string          `json:"source_url"`
	SourceType   ContentSource    `json:"source_type"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

type GameLocalization struct {
	ContentID uuid.UUID `json:"content_id"`
	Lang      Locale    `json:"lang"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type GameNote struct {
	ID               uuid.UUID      `json:"id"`
	CreatedAt        time.Time      `json:"created_at"`
	CreatedBy        uuid.UUID      `json:"created_by"`
	UpdatedAt        time.Time      `json:"updated_at"`
	UpdatedBy        uuid.UUID      `json:"updated_by"`
	UserID           uuid.UUID      `json:"user_id"`
	ContentID        uuid.UUID      `json:"content_id"`
	Rate             *int16         `json:"rate"`
	Comment          *string        `json:"comment"`
	InitialOrdererID uuid.UUID      `json:"initial_orderer_id"`
	Status           GameNoteStatus `json:"status"`
	LastPlayedAt     *time.Time     `json:"last_played_at"`
}

type GameNoteOrder struct {
	GameNoteID uuid.UUID  `json:"game_note_id"`
	OrderID    uuid.UUID  `json:"order_id"`
	CreatedAt  time.Time  `json:"created_at"`
	CreatedBy  *uuid.UUID `json:"created_by"`
	UpdatedAt  time.Time  `json:"updated_at"`
	UpdatedBy  *uuid.UUID `json:"updated_by"`
}

type GameNoteReaction struct {
	GameNoteID uuid.UUID      `json:"game_note_id"`
	UserID     uuid.UUID      `json:"user_id"`
	EmoteID    string         `json:"emote_id"`
	Source     ReactionSource `json:"source"`
	CreatedAt  time.Time      `json:"created_at"`
	CreatedBy  uuid.UUID      `json:"created_by"`
}

type GamesViewEn struct {
	ID          uuid.UUID  `json:"id"`
	ExternalID  int64      `json:"external_id"`
	Title       string     `json:"title"`
	ReleaseDate *time.Time `json:"release_date"`
	Websites    []byte     `json:"websites"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type GamesViewRu struct {
	ID          uuid.UUID  `json:"id"`
	ExternalID  int64      `json:"external_id"`
	Title       string     `json:"title"`
	ReleaseDate *time.Time `json:"release_date"`
	Websites    []byte     `json:"websites"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type IgdbSyncLog struct {
	ID             uuid.UUID      `json:"id"`
	SyncType       IgdbSyncType   `json:"sync_type"`
	Status         IgdbSyncStatus `json:"status"`
	StartedAt      time.Time      `json:"started_at"`
	GamesProcessed int64          `json:"games_processed"`
	CompletedAt    *time.Time     `json:"completed_at"`
	ErrorMessage   *string        `json:"error_message"`
}

type Moderator struct {
	ID          uuid.UUID  `json:"id"`
	CreatedAt   time.Time  `json:"created_at"`
	CreatedBy   uuid.UUID  `json:"created_by"`
	DeletedAt   *time.Time `json:"deleted_at"`
	DeletedBy   *uuid.UUID `json:"deleted_by"`
	UserID      uuid.UUID  `json:"user_id"`
	ModeratorID uuid.UUID  `json:"moderator_id"`
}

type Movie struct {
	ID           uuid.UUID        `json:"id"`
	ExternalID   int64            `json:"external_id"`
	ReleaseDate  *time.Time       `json:"release_date"`
	Websites     []byte           `json:"websites"`
	CoverKey     *string          `json:"cover_key"`
	CoverKeyType NullImageKeyType `json:"cover_key_type"`
	SourceUrl    *string          `json:"source_url"`
	SourceType   ContentSource    `json:"source_type"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

type MovieLocalization struct {
	ContentID uuid.UUID `json:"content_id"`
	Lang      Locale    `json:"lang"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type MovieNote struct {
	ID               uuid.UUID       `json:"id"`
	CreatedAt        time.Time       `json:"created_at"`
	CreatedBy        uuid.UUID       `json:"created_by"`
	UpdatedAt        time.Time       `json:"updated_at"`
	UpdatedBy        uuid.UUID       `json:"updated_by"`
	UserID           uuid.UUID       `json:"user_id"`
	ContentID        uuid.UUID       `json:"content_id"`
	Rate             *int16          `json:"rate"`
	Comment          *string         `json:"comment"`
	Status           MovieNoteStatus `json:"status"`
	InitialOrdererID uuid.UUID       `json:"initial_orderer_id"`
	WatchedAt        *time.Time      `json:"watched_at"`
}

type MovieNoteOrder struct {
	MovieNoteID uuid.UUID  `json:"movie_note_id"`
	OrderID     uuid.UUID  `json:"order_id"`
	CreatedAt   time.Time  `json:"created_at"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	UpdatedAt   time.Time  `json:"updated_at"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

type MovieNoteReaction struct {
	MovieNoteID uuid.UUID      `json:"movie_note_id"`
	UserID      uuid.UUID      `json:"user_id"`
	EmoteID     string         `json:"emote_id"`
	Source      ReactionSource `json:"source"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   *uuid.UUID     `json:"created_by"`
}

type Order struct {
	ID          uuid.UUID       `json:"id"`
	CreatedAt   time.Time       `json:"created_at"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	UpdatedAt   time.Time       `json:"updated_at"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
	ReceiverID  uuid.UUID       `json:"receiver_id"`
	PaymentType int16           `json:"payment_type"`
	Amount      float32         `json:"amount"`
	Status      OrderStatus     `json:"status"`
	OrdererID   uuid.UUID       `json:"orderer_id"`
	Message     string          `json:"message"`
	Category    ContentCategory `json:"category"`
	Anonymous   bool            `json:"anonymous"`
	Source      string          `json:"source"`
	Reference   []byte          `json:"reference"`
}

type Orderer struct {
	ID              uuid.UUID  `json:"id"`
	CreatedAt       time.Time  `json:"created_at"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	UpdatedAt       time.Time  `json:"updated_at"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
	UserID          *uuid.UUID `json:"user_id"`
	DisplayName     string     `json:"display_name"`
	Source          string     `json:"source"`
	ReferenceUserID *string    `json:"reference_user_id"`
}

type PosterPreview struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	CreatedBy uuid.UUID `json:"created_by"`
	ObjectKey string    `json:"object_key"`
}

type Profile struct {
	UserID                uuid.UUID  `json:"user_id"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
	UpdatedBy             *uuid.UUID `json:"updated_by"`
	DisplayName           string     `json:"display_name"`
	Username              string     `json:"username"`
	Description           string     `json:"description"`
	SuggestionPreferences []byte     `json:"suggestion_preferences"`
}

type ProfileAvatar struct {
	UserID           uuid.UUID  `json:"user_id"`
	CreatedAt        time.Time  `json:"created_at"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	UpdatedAt        time.Time  `json:"updated_at"`
	UpdatedBy        *uuid.UUID `json:"updated_by"`
	AvatarKey        *string    `json:"avatar_key"`
	AvatarUrl        *string    `json:"avatar_url"`
	AvatarPreviewKey *string    `json:"avatar_preview_key"`
}
