// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type EsMigrationLog struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type GameNote struct {
	ID               uuid.UUID  `json:"id"`
	CreatedAt        time.Time  `json:"created_at"`
	CreatedBy        uuid.UUID  `json:"created_by"`
	UpdatedAt        time.Time  `json:"updated_at"`
	UpdatedBy        uuid.UUID  `json:"updated_by"`
	UserID           uuid.UUID  `json:"user_id"`
	GameID           *uuid.UUID `json:"game_id"`
	Name             string     `json:"name"`
	Link             *string    `json:"link"`
	ReleaseDate      *time.Time `json:"release_date"`
	Rate             *int16     `json:"rate"`
	Comment          *string    `json:"comment"`
	Ordered          bool       `json:"ordered"`
	Status           int16      `json:"status"`
	CompletionStatus int16      `json:"completion_status"`
	CompletionDate   *time.Time `json:"completion_date"`
}

type GameNoteOrder struct {
	GameNoteID uuid.UUID `json:"game_note_id"`
	OrderID    uuid.UUID `json:"order_id"`
	CreatedAt  time.Time `json:"created_at"`
	CreatedBy  uuid.UUID `json:"created_by"`
	UpdatedAt  time.Time `json:"updated_at"`
	UpdatedBy  uuid.UUID `json:"updated_by"`
}

type MigrationLog struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	ID              uuid.UUID `json:"id"`
	CreatedAt       time.Time `json:"created_at"`
	CreatedBy       uuid.UUID `json:"created_by"`
	UpdatedAt       time.Time `json:"updated_at"`
	UpdatedBy       uuid.UUID `json:"updated_by"`
	ReceiverID      uuid.UUID `json:"receiver_id"`
	PaymentType     int16     `json:"payment_type"`
	Amount          float32   `json:"amount"`
	Status          int16     `json:"status"`
	OrdererID       uuid.UUID `json:"orderer_id"`
	OrdererUsername string    `json:"orderer_username"`
	Category        int16     `json:"category"`
	Message         string    `json:"message"`
}

type Orderer struct {
	ID        uuid.UUID  `json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	CreatedBy *uuid.UUID `json:"created_by"`
	UpdatedAt time.Time  `json:"updated_at"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	UserID    *uuid.UUID `json:"user_id"`
	Username  string     `json:"username"`
	Anonymous bool       `json:"anonymous"`
}

type Profile struct {
	UserID    uuid.UUID  `json:"user_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	Username  string     `json:"username"`
	Link      string     `json:"link"`
}
