// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: movie_notes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countWatchedMovieNotesByUserId = `-- name: CountWatchedMovieNotesByUserId :one
SELECT COUNT(*) AS "count"
FROM "movie_notes"
WHERE "user_id" = $1::uuid
    AND "status" = 'watched'
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) CountWatchedMovieNotesByUserId(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWatchedMovieNotesByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMovieNoteById = `-- name: DeleteMovieNoteById :exec
DELETE FROM "movie_notes"
WHERE "id" = $1::uuid
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) DeleteMovieNoteById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMovieNoteById, id)
	return err
}

const findMovieNoteById = `-- name: FindMovieNoteById :one
SELECT id, user_id, name, release_date, rate, comment, status, initial_orderer_id, watched_at, poster_key, poster_updated_at, created_at, created_by, updated_at, updated_by
FROM "movie_notes"
WHERE "id" = $1::uuid
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindMovieNoteById(ctx context.Context, id uuid.UUID) (*MovieNote, error) {
	row := q.db.QueryRow(ctx, findMovieNoteById, id)
	var i MovieNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ReleaseDate,
		&i.Rate,
		&i.Comment,
		&i.Status,
		&i.InitialOrdererID,
		&i.WatchedAt,
		&i.PosterKey,
		&i.PosterUpdatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return &i, err
}

const findPaginatedMovieNotesByUserId = `-- name: FindPaginatedMovieNotesByUserId :many
SELECT 
    mn."id",
    mn."created_at",
    mn."name",
    mn."status",
    mn."rate",
    mn."comment",
    mn."release_date",
    mn."watched_at",
    o."username" AS "initial_orderer_username",
    COALESCE(order_counts."count", 0) AS "orderer_count"
FROM "movie_notes" mn
LEFT JOIN "orderers" o ON mn."initial_orderer_id" = o."id"
LEFT JOIN (
    SELECT 
        "movie_note_id",
        COUNT(*) AS "count"
    FROM "movie_note_orders"
    GROUP BY "movie_note_id"
) AS order_counts ON mn."id" = order_counts."movie_note_id"
WHERE mn."user_id" = $1::uuid
ORDER BY mn."created_at" DESC
LIMIT $2::int
`

type FindPaginatedMovieNotesByUserIdParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type FindPaginatedMovieNotesByUserIdRow struct {
	ID                     uuid.UUID       `json:"id"`
	CreatedAt              time.Time       `json:"created_at"`
	Name                   string          `json:"name"`
	Status                 MovieNoteStatus `json:"status"`
	Rate                   *int16          `json:"rate"`
	Comment                *string         `json:"comment"`
	ReleaseDate            *time.Time      `json:"release_date"`
	WatchedAt              *time.Time      `json:"watched_at"`
	InitialOrdererUsername *string         `json:"initial_orderer_username"`
	OrdererCount           int64           `json:"orderer_count"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindPaginatedMovieNotesByUserId(ctx context.Context, arg FindPaginatedMovieNotesByUserIdParams) ([]*FindPaginatedMovieNotesByUserIdRow, error) {
	rows, err := q.db.Query(ctx, findPaginatedMovieNotesByUserId, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindPaginatedMovieNotesByUserIdRow{}
	for rows.Next() {
		var i FindPaginatedMovieNotesByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Status,
			&i.Rate,
			&i.Comment,
			&i.ReleaseDate,
			&i.WatchedAt,
			&i.InitialOrdererUsername,
			&i.OrdererCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMovieNote = `-- name: InsertMovieNote :one
INSERT INTO "movie_notes" (
    "user_id",
    "name",
    "release_date",
    "rate",
    "comment",
    "status",
    "initial_orderer_id",
    "watched_at",
    "poster_key",
    "created_by",
    "updated_by"
) VALUES (
    $1::uuid,
    $2::text,
    $3::timestamptz,
    $4::smallint,
    $5::text,
    $6::movie_note_status,
    $7::uuid,
    $8::timestamptz,
    $9::text,
    $10::uuid,
    $10::uuid
)
RETURNING id, user_id, name, release_date, rate, comment, status, initial_orderer_id, watched_at, poster_key, poster_updated_at, created_at, created_by, updated_at, updated_by
`

type InsertMovieNoteParams struct {
	UserID           uuid.UUID       `json:"user_id"`
	Name             string          `json:"name"`
	ReleaseDate      *time.Time      `json:"release_date"`
	Rate             *int16          `json:"rate"`
	Comment          *string         `json:"comment"`
	Status           MovieNoteStatus `json:"status"`
	InitialOrdererID uuid.UUID       `json:"initial_orderer_id"`
	WatchedAt        *time.Time      `json:"watched_at"`
	PosterKey        *string         `json:"poster_key"`
	CreatedBy        uuid.UUID       `json:"created_by"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertMovieNote(ctx context.Context, arg InsertMovieNoteParams) (*MovieNote, error) {
	row := q.db.QueryRow(ctx, insertMovieNote,
		arg.UserID,
		arg.Name,
		arg.ReleaseDate,
		arg.Rate,
		arg.Comment,
		arg.Status,
		arg.InitialOrdererID,
		arg.WatchedAt,
		arg.PosterKey,
		arg.CreatedBy,
	)
	var i MovieNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ReleaseDate,
		&i.Rate,
		&i.Comment,
		&i.Status,
		&i.InitialOrdererID,
		&i.WatchedAt,
		&i.PosterKey,
		&i.PosterUpdatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return &i, err
}

const updateMovieNoteById = `-- name: UpdateMovieNoteById :exec
UPDATE "movie_notes"
SET "updated_by" = $1::uuid,
    "updated_at" = now(),
    "name" = $2::text,
    "release_date" = $3::timestamptz,
    "rate" = $4::smallint,
    "comment" = $5::text,
    "status" = $6::movie_note_status,
    "watched_at" = $7::timestamptz,
    "poster_key" = $8::text
WHERE "id" = $9::uuid
`

type UpdateMovieNoteByIdParams struct {
	UpdatedBy   uuid.UUID       `json:"updated_by"`
	Name        string          `json:"name"`
	ReleaseDate *time.Time      `json:"release_date"`
	Rate        *int16          `json:"rate"`
	Comment     *string         `json:"comment"`
	Status      MovieNoteStatus `json:"status"`
	WatchedAt   *time.Time      `json:"watched_at"`
	PosterKey   *string         `json:"poster_key"`
	ID          uuid.UUID       `json:"id"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) UpdateMovieNoteById(ctx context.Context, arg UpdateMovieNoteByIdParams) error {
	_, err := q.db.Exec(ctx, updateMovieNoteById,
		arg.UpdatedBy,
		arg.Name,
		arg.ReleaseDate,
		arg.Rate,
		arg.Comment,
		arg.Status,
		arg.WatchedAt,
		arg.PosterKey,
		arg.ID,
	)
	return err
}

const updateMovieNoteName = `-- name: UpdateMovieNoteName :one
UPDATE "movie_notes"
SET "name" = $1::text,
    "updated_by" = $2::uuid,
    "updated_at" = now()
WHERE "id" = $3::uuid
RETURNING id, user_id, name, release_date, rate, comment, status, initial_orderer_id, watched_at, poster_key, poster_updated_at, created_at, created_by, updated_at, updated_by
`

type UpdateMovieNoteNameParams struct {
	Name      string    `json:"name"`
	UpdatedBy uuid.UUID `json:"updated_by"`
	ID        uuid.UUID `json:"id"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) UpdateMovieNoteName(ctx context.Context, arg UpdateMovieNoteNameParams) (*MovieNote, error) {
	row := q.db.QueryRow(ctx, updateMovieNoteName, arg.Name, arg.UpdatedBy, arg.ID)
	var i MovieNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ReleaseDate,
		&i.Rate,
		&i.Comment,
		&i.Status,
		&i.InitialOrdererID,
		&i.WatchedAt,
		&i.PosterKey,
		&i.PosterUpdatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return &i, err
}
