// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: movie_note_reactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addMovieNoteReaction = `-- name: AddMovieNoteReaction :exec
INSERT INTO movie_note_reactions (
        movie_note_id,
        user_id,
        emote_id,
        source
    )
VALUES (
        $1::uuid,
        $2::uuid,
        $3::text,
        $4::reaction_source
    )
`

type AddMovieNoteReactionParams struct {
	MovieNoteID uuid.UUID      `json:"movie_note_id"`
	UserID      uuid.UUID      `json:"user_id"`
	EmoteID     string         `json:"emote_id"`
	Source      ReactionSource `json:"source"`
}

func (q *Queries) AddMovieNoteReaction(ctx context.Context, arg AddMovieNoteReactionParams) error {
	_, err := q.db.Exec(ctx, addMovieNoteReaction,
		arg.MovieNoteID,
		arg.UserID,
		arg.EmoteID,
		arg.Source,
	)
	return err
}

const countMovieNoteReactionsByMovieNoteIDAndUserID = `-- name: CountMovieNoteReactionsByMovieNoteIDAndUserID :one
SELECT COUNT(*)
FROM movie_note_reactions
WHERE movie_note_id = $1::uuid
    AND user_id = $2::uuid
`

type CountMovieNoteReactionsByMovieNoteIDAndUserIDParams struct {
	MovieNoteID uuid.UUID `json:"movie_note_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) CountMovieNoteReactionsByMovieNoteIDAndUserID(ctx context.Context, arg CountMovieNoteReactionsByMovieNoteIDAndUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMovieNoteReactionsByMovieNoteIDAndUserID, arg.MovieNoteID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMovieNoteReactionsByMovieNoteIDInAndUserID = `-- name: GetMovieNoteReactionsByMovieNoteIDInAndUserID :many
SELECT mnr.movie_note_id,
    mnr.emote_id,
    mnr.source,
    COUNT(DISTINCT mnr.user_id) AS count,
    COALESCE(
        (
            SELECT 1
            FROM movie_note_reactions r2
            WHERE r2.movie_note_id = mnr.movie_note_id
                AND r2.user_id = $1::uuid
                AND r2.emote_id = mnr.emote_id
                AND r2.source = mnr.source
        ),
        0
    ) AS reacted_by_user
FROM movie_note_reactions mnr
WHERE mnr.movie_note_id = ANY($2::uuid [])
GROUP BY mnr.movie_note_id,
    mnr.emote_id,
    mnr.source
ORDER BY count DESC
`

type GetMovieNoteReactionsByMovieNoteIDInAndUserIDParams struct {
	UserID       *uuid.UUID  `json:"user_id"`
	MovieNoteIds []uuid.UUID `json:"movie_note_ids"`
}

type GetMovieNoteReactionsByMovieNoteIDInAndUserIDRow struct {
	MovieNoteID   uuid.UUID      `json:"movie_note_id"`
	EmoteID       string         `json:"emote_id"`
	Source        ReactionSource `json:"source"`
	Count         int64          `json:"count"`
	ReactedByUser *int32         `json:"reacted_by_user"`
}

func (q *Queries) GetMovieNoteReactionsByMovieNoteIDInAndUserID(ctx context.Context, arg GetMovieNoteReactionsByMovieNoteIDInAndUserIDParams) ([]*GetMovieNoteReactionsByMovieNoteIDInAndUserIDRow, error) {
	rows, err := q.db.Query(ctx, getMovieNoteReactionsByMovieNoteIDInAndUserID, arg.UserID, arg.MovieNoteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetMovieNoteReactionsByMovieNoteIDInAndUserIDRow{}
	for rows.Next() {
		var i GetMovieNoteReactionsByMovieNoteIDInAndUserIDRow
		if err := rows.Scan(
			&i.MovieNoteID,
			&i.EmoteID,
			&i.Source,
			&i.Count,
			&i.ReactedByUser,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMovieNoteReaction = `-- name: RemoveMovieNoteReaction :exec
DELETE FROM movie_note_reactions
WHERE movie_note_id = $1::uuid
    AND user_id = $2::uuid
    AND emote_id = $3::text
    AND source = $4::reaction_source
`

type RemoveMovieNoteReactionParams struct {
	MovieNoteID uuid.UUID      `json:"movie_note_id"`
	UserID      uuid.UUID      `json:"user_id"`
	EmoteID     string         `json:"emote_id"`
	Source      ReactionSource `json:"source"`
}

func (q *Queries) RemoveMovieNoteReaction(ctx context.Context, arg RemoveMovieNoteReactionParams) error {
	_, err := q.db.Exec(ctx, removeMovieNoteReaction,
		arg.MovieNoteID,
		arg.UserID,
		arg.EmoteID,
		arg.Source,
	)
	return err
}
