// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: movie_note_orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countOrdersByMovieNoteId = `-- name: CountOrdersByMovieNoteId :one
SELECT COUNT(*) AS "total"
FROM "movie_note_orders"
WHERE "movie_note_id" = $1::uuid
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) CountOrdersByMovieNoteId(ctx context.Context, movieNoteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByMovieNoteId, movieNoteID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertMovieNoteOrder = `-- name: InsertMovieNoteOrder :one
INSERT INTO "movie_note_orders" (
    "movie_note_id",
    "order_id",
    "created_by"
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid
)
RETURNING movie_note_id, order_id, created_at, created_by
`

type InsertMovieNoteOrderParams struct {
	MovieNoteID uuid.UUID `json:"movie_note_id"`
	OrderID     uuid.UUID `json:"order_id"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertMovieNoteOrder(ctx context.Context, arg InsertMovieNoteOrderParams) (*MovieNoteOrder, error) {
	row := q.db.QueryRow(ctx, insertMovieNoteOrder, arg.MovieNoteID, arg.OrderID, arg.CreatedBy)
	var i MovieNoteOrder
	err := row.Scan(
		&i.MovieNoteID,
		&i.OrderID,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return &i, err
}

const resetApprovedOrdersByMovieNoteId = `-- name: ResetApprovedOrdersByMovieNoteId :exec
UPDATE "orders"
SET "status" = 'pending'
WHERE "id" IN (
    SELECT "order_id"
    FROM "movie_note_orders"
    WHERE "movie_note_id" = $1::uuid
)
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) ResetApprovedOrdersByMovieNoteId(ctx context.Context, movieNoteID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetApprovedOrdersByMovieNoteId, movieNoteID)
	return err
}
