// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: movies.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies
WHERE id = $1::uuid
`

func (q *Queries) DeleteMovie(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMovie, id)
	return err
}

const deleteMovieLocalization = `-- name: DeleteMovieLocalization :exec
DELETE FROM movie_localizations
WHERE content_id = $1::uuid
    AND lang = $2::locale
`

type DeleteMovieLocalizationParams struct {
	ContentID uuid.UUID `json:"content_id"`
	Lang      Locale    `json:"lang"`
}

func (q *Queries) DeleteMovieLocalization(ctx context.Context, arg DeleteMovieLocalizationParams) error {
	_, err := q.db.Exec(ctx, deleteMovieLocalization, arg.ContentID, arg.Lang)
	return err
}

const findMovieByID = `-- name: FindMovieByID :one
SELECT id, external_id, release_date, websites, cover_key, cover_key_type, source_url, source_type, created_at, updated_at
FROM movies
WHERE id = $1::uuid
`

func (q *Queries) FindMovieByID(ctx context.Context, id uuid.UUID) (*Movie, error) {
	row := q.db.QueryRow(ctx, findMovieByID, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ReleaseDate,
		&i.Websites,
		&i.CoverKey,
		&i.CoverKeyType,
		&i.SourceUrl,
		&i.SourceType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findMovieByIDWithLocalization = `-- name: FindMovieByIDWithLocalization :one
SELECT movies.id, movies.external_id, movies.release_date, movies.websites, movies.cover_key, movies.cover_key_type, movies.source_url, movies.source_type, movies.created_at, movies.updated_at,
    movie_localizations.title AS title
FROM movies
    JOIN movie_localizations ON movies.id = movie_localizations.content_id
    AND movie_localizations.lang = $1::locale
WHERE movies.id = $2::uuid
`

type FindMovieByIDWithLocalizationParams struct {
	Lang Locale    `json:"lang"`
	ID   uuid.UUID `json:"id"`
}

type FindMovieByIDWithLocalizationRow struct {
	ID           uuid.UUID        `json:"id"`
	ExternalID   int64            `json:"external_id"`
	ReleaseDate  *time.Time       `json:"release_date"`
	Websites     *[]byte          `json:"websites"`
	CoverKey     *string          `json:"cover_key"`
	CoverKeyType NullImageKeyType `json:"cover_key_type"`
	SourceUrl    *string          `json:"source_url"`
	SourceType   ContentSource    `json:"source_type"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
	Title        string           `json:"title"`
}

func (q *Queries) FindMovieByIDWithLocalization(ctx context.Context, arg FindMovieByIDWithLocalizationParams) (*FindMovieByIDWithLocalizationRow, error) {
	row := q.db.QueryRow(ctx, findMovieByIDWithLocalization, arg.Lang, arg.ID)
	var i FindMovieByIDWithLocalizationRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.ReleaseDate,
		&i.Websites,
		&i.CoverKey,
		&i.CoverKeyType,
		&i.SourceUrl,
		&i.SourceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return &i, err
}

const upsertMovie = `-- name: UpsertMovie :one
INSERT INTO movies (
        external_id,
        release_date,
        websites,
        cover_key,
        cover_key_type,
        source_url,
        source_type
    )
VALUES (
        $1::bigint,
        $2::timestamptz,
        $3::jsonb,
        $4::text,
        $5::image_key_type,
        $6::text,
        $7::content_source
    ) ON CONFLICT (external_id) DO
UPDATE
SET release_date = $2::timestamptz,
    cover_key = $4::text,
    cover_key_type = $5::image_key_type,
    source_url = $6::text,
    source_type = $7::content_source,
    updated_at = now()
RETURNING id
`

type UpsertMovieParams struct {
	ExternalID   int64            `json:"external_id"`
	ReleaseDate  *time.Time       `json:"release_date"`
	Websites     *[]byte          `json:"websites"`
	CoverKey     *string          `json:"cover_key"`
	CoverKeyType NullImageKeyType `json:"cover_key_type"`
	SourceUrl    *string          `json:"source_url"`
	SourceType   ContentSource    `json:"source_type"`
}

func (q *Queries) UpsertMovie(ctx context.Context, arg UpsertMovieParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertMovie,
		arg.ExternalID,
		arg.ReleaseDate,
		arg.Websites,
		arg.CoverKey,
		arg.CoverKeyType,
		arg.SourceUrl,
		arg.SourceType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertMovieLocalization = `-- name: UpsertMovieLocalization :exec
INSERT INTO movie_localizations (content_id, lang, title)
VALUES (
        $1::uuid,
        $2::locale,
        $3::text
    ) ON CONFLICT (content_id, lang) DO
UPDATE
SET title = $3::text,
    updated_at = now()
`

type UpsertMovieLocalizationParams struct {
	ContentID uuid.UUID `json:"content_id"`
	Lang      Locale    `json:"lang"`
	Title     string    `json:"title"`
}

func (q *Queries) UpsertMovieLocalization(ctx context.Context, arg UpsertMovieLocalizationParams) error {
	_, err := q.db.Exec(ctx, upsertMovieLocalization, arg.ContentID, arg.Lang, arg.Title)
	return err
}
