// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countOrdersByReceiverId = `-- name: CountOrdersByReceiverId :one
SELECT COUNT(*) AS "total" FROM "orders" WHERE "receiver_id" = $1
`

// Author: Egor Kuzmin (keelfy)
// Counts orders by receiver id
func (q *Queries) CountOrdersByReceiverId(ctx context.Context, receiverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByReceiverId, receiverID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const findLastOrdersByReceiverId = `-- name: FindLastOrdersByReceiverId :many
SELECT id, created_at, created_by, updated_at, updated_by, receiver_id, payment_type, amount, status, orderer_id, orderer_username, message, category, updated_message, updated_category
FROM "orders"
WHERE "receiver_id" = $1
ORDER BY "created_at" DESC
LIMIT $2
`

type FindLastOrdersByReceiverIdParams struct {
	ReceiverID uuid.UUID `json:"receiver_id"`
	Limit      int32     `json:"limit"`
}

// Author: Egor Kuzmin (keelfy)
// Queries last orders by receiver id
func (q *Queries) FindLastOrdersByReceiverId(ctx context.Context, arg FindLastOrdersByReceiverIdParams) ([]*Order, error) {
	rows, err := q.db.Query(ctx, findLastOrdersByReceiverId, arg.ReceiverID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.ReceiverID,
			&i.PaymentType,
			&i.Amount,
			&i.Status,
			&i.OrdererID,
			&i.OrdererUsername,
			&i.Message,
			&i.Category,
			&i.UpdatedMessage,
			&i.UpdatedCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrderById = `-- name: FindOrderById :one
SELECT id, created_at, created_by, updated_at, updated_by, receiver_id, payment_type, amount, status, orderer_id, orderer_username, message, category, updated_message, updated_category FROM "orders" WHERE "id" = $1
`

// Author: Egor Kuzmin (keelfy)
// Queries order by id
func (q *Queries) FindOrderById(ctx context.Context, id uuid.UUID) (*Order, error) {
	row := q.db.QueryRow(ctx, findOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.ReceiverID,
		&i.PaymentType,
		&i.Amount,
		&i.Status,
		&i.OrdererID,
		&i.OrdererUsername,
		&i.Message,
		&i.Category,
		&i.UpdatedMessage,
		&i.UpdatedCategory,
	)
	return &i, err
}

const findOrdersByReceiverId = `-- name: FindOrdersByReceiverId :many
SELECT id, created_at, created_by, updated_at, updated_by, receiver_id, payment_type, amount, status, orderer_id, orderer_username, message, category, updated_message, updated_category
FROM "orders"
WHERE "receiver_id" = $1
`

// Author: Egor Kuzmin (keelfy)
// Queries orders by receiver id
func (q *Queries) FindOrdersByReceiverId(ctx context.Context, receiverID uuid.UUID) ([]*Order, error) {
	rows, err := q.db.Query(ctx, findOrdersByReceiverId, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.ReceiverID,
			&i.PaymentType,
			&i.Amount,
			&i.Status,
			&i.OrdererID,
			&i.OrdererUsername,
			&i.Message,
			&i.Category,
			&i.UpdatedMessage,
			&i.UpdatedCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPaginatedOrdersByGameNoteId = `-- name: FindPaginatedOrdersByGameNoteId :many
SELECT orders.id, orders.created_at, orders.created_by, orders.updated_at, orders.updated_by, orders.receiver_id, orders.payment_type, orders.amount, orders.status, orders.orderer_id, orders.orderer_username, orders.message, orders.category, orders.updated_message, orders.updated_category
FROM "orders"
    INNER JOIN "game_note_orders" ON 
        "game_note_orders"."order_id" = "orders"."id"
        AND "game_note_orders"."game_note_id" = $1
ORDER BY "game_note_orders"."created_at" DESC
LIMIT $2
OFFSET $3
`

type FindPaginatedOrdersByGameNoteIdParams struct {
	GameNoteID uuid.UUID `json:"game_note_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindPaginatedOrdersByGameNoteId(ctx context.Context, arg FindPaginatedOrdersByGameNoteIdParams) ([]*Order, error) {
	rows, err := q.db.Query(ctx, findPaginatedOrdersByGameNoteId, arg.GameNoteID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.ReceiverID,
			&i.PaymentType,
			&i.Amount,
			&i.Status,
			&i.OrdererID,
			&i.OrdererUsername,
			&i.Message,
			&i.Category,
			&i.UpdatedMessage,
			&i.UpdatedCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO "orders" (
    "created_by",
    "updated_by",
    "receiver_id",
    "payment_type",
    "amount",
    "status",
    "orderer_id",
    "orderer_username",
    "category",
    "message"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, created_at, created_by, updated_at, updated_by, receiver_id, payment_type, amount, status, orderer_id, orderer_username, message, category, updated_message, updated_category
`

type InsertOrderParams struct {
	CreatedBy       uuid.UUID       `json:"created_by"`
	UpdatedBy       uuid.UUID       `json:"updated_by"`
	ReceiverID      uuid.UUID       `json:"receiver_id"`
	PaymentType     int16           `json:"payment_type"`
	Amount          float32         `json:"amount"`
	Status          OrderStatus     `json:"status"`
	OrdererID       uuid.UUID       `json:"orderer_id"`
	OrdererUsername string          `json:"orderer_username"`
	Category        ContentCategory `json:"category"`
	Message         string          `json:"message"`
}

// Author: Egor Kuzmin (keelfy)
// Inserts a new order
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (*Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.ReceiverID,
		arg.PaymentType,
		arg.Amount,
		arg.Status,
		arg.OrdererID,
		arg.OrdererUsername,
		arg.Category,
		arg.Message,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.ReceiverID,
		&i.PaymentType,
		&i.Amount,
		&i.Status,
		&i.OrdererID,
		&i.OrdererUsername,
		&i.Message,
		&i.Category,
		&i.UpdatedMessage,
		&i.UpdatedCategory,
	)
	return &i, err
}

const updateOrderById = `-- name: UpdateOrderById :one
UPDATE "orders"
SET "updated_at" = now(),
    "updated_by" = $2,
    "status" = $3,
    "updated_message" = $4,
    "updated_category" = $5
WHERE "id" = $1
RETURNING id, created_at, created_by, updated_at, updated_by, receiver_id, payment_type, amount, status, orderer_id, orderer_username, message, category, updated_message, updated_category
`

type UpdateOrderByIdParams struct {
	ID              uuid.UUID           `json:"id"`
	UpdatedBy       uuid.UUID           `json:"updated_by"`
	Status          OrderStatus         `json:"status"`
	UpdatedMessage  *string             `json:"updated_message"`
	UpdatedCategory NullContentCategory `json:"updated_category"`
}

// Author: Egor Kuzmin (keelfy)
// Updates order, updated_at and updated_by
func (q *Queries) UpdateOrderById(ctx context.Context, arg UpdateOrderByIdParams) (*Order, error) {
	row := q.db.QueryRow(ctx, updateOrderById,
		arg.ID,
		arg.UpdatedBy,
		arg.Status,
		arg.UpdatedMessage,
		arg.UpdatedCategory,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.ReceiverID,
		&i.PaymentType,
		&i.Amount,
		&i.Status,
		&i.OrdererID,
		&i.OrdererUsername,
		&i.Message,
		&i.Category,
		&i.UpdatedMessage,
		&i.UpdatedCategory,
	)
	return &i, err
}
