// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOrdersByReceiverID = `-- name: CountOrdersByReceiverID :one
SELECT COUNT(*) AS total
FROM orders
WHERE receiver_id = $1::uuid
`

func (q *Queries) CountOrdersByReceiverID(ctx context.Context, receiverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByReceiverID, receiverID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const findLastOrdersByReceiverID = `-- name: FindLastOrdersByReceiverID :many
SELECT o.id,
    o.created_at,
    o.payment_type,
    o.amount,
    o.status,
    o.message,
    o.category
FROM orders o
WHERE o.receiver_id = $1::uuid
ORDER BY o.created_at DESC
LIMIT $2::bigint
`

type FindLastOrdersByReceiverIDParams struct {
	ReceiverID uuid.UUID `json:"receiver_id"`
	Limit      int64     `json:"limit"`
}

type FindLastOrdersByReceiverIDRow struct {
	ID          uuid.UUID       `json:"id"`
	CreatedAt   time.Time       `json:"created_at"`
	PaymentType int16           `json:"payment_type"`
	Amount      float32         `json:"amount"`
	Status      OrderStatus     `json:"status"`
	Message     string          `json:"message"`
	Category    ContentCategory `json:"category"`
}

func (q *Queries) FindLastOrdersByReceiverID(ctx context.Context, arg FindLastOrdersByReceiverIDParams) ([]*FindLastOrdersByReceiverIDRow, error) {
	rows, err := q.db.Query(ctx, findLastOrdersByReceiverID, arg.ReceiverID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindLastOrdersByReceiverIDRow{}
	for rows.Next() {
		var i FindLastOrdersByReceiverIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.PaymentType,
			&i.Amount,
			&i.Status,
			&i.Message,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrderByID = `-- name: FindOrderByID :one
SELECT o.id, o.created_at, o.created_by, o.updated_at, o.updated_by, o.receiver_id, o.payment_type, o.amount, o.status, o.orderer_id, o.message, o.category, o.anonymous, o.source, o.reference,
    orer.display_name AS orderer_display_name
FROM orders o
    LEFT JOIN orderers orer ON orer.id = o.orderer_id
WHERE o.id = $1::uuid
`

type FindOrderByIDRow struct {
	ID                 uuid.UUID       `json:"id"`
	CreatedAt          time.Time       `json:"created_at"`
	CreatedBy          *uuid.UUID      `json:"created_by"`
	UpdatedAt          time.Time       `json:"updated_at"`
	UpdatedBy          *uuid.UUID      `json:"updated_by"`
	ReceiverID         uuid.UUID       `json:"receiver_id"`
	PaymentType        int16           `json:"payment_type"`
	Amount             float32         `json:"amount"`
	Status             OrderStatus     `json:"status"`
	OrdererID          uuid.UUID       `json:"orderer_id"`
	Message            string          `json:"message"`
	Category           ContentCategory `json:"category"`
	Anonymous          bool            `json:"anonymous"`
	Source             string          `json:"source"`
	Reference          []byte          `json:"reference"`
	OrdererDisplayName *string         `json:"orderer_display_name"`
}

func (q *Queries) FindOrderByID(ctx context.Context, id uuid.UUID) (*FindOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, findOrderByID, id)
	var i FindOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.ReceiverID,
		&i.PaymentType,
		&i.Amount,
		&i.Status,
		&i.OrdererID,
		&i.Message,
		&i.Category,
		&i.Anonymous,
		&i.Source,
		&i.Reference,
		&i.OrdererDisplayName,
	)
	return &i, err
}

const findOrdersByReceiverID = `-- name: FindOrdersByReceiverID :many
SELECT id, created_at, created_by, updated_at, updated_by, receiver_id, payment_type, amount, status, orderer_id, message, category, anonymous, source, reference
FROM orders
WHERE receiver_id = $1::uuid
`

func (q *Queries) FindOrdersByReceiverID(ctx context.Context, receiverID uuid.UUID) ([]*Order, error) {
	rows, err := q.db.Query(ctx, findOrdersByReceiverID, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.ReceiverID,
			&i.PaymentType,
			&i.Amount,
			&i.Status,
			&i.OrdererID,
			&i.Message,
			&i.Category,
			&i.Anonymous,
			&i.Source,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPaginatedOrdersByGameNoteID = `-- name: FindPaginatedOrdersByGameNoteID :many
SELECT orders.id, orders.created_at, orders.created_by, orders.updated_at, orders.updated_by, orders.receiver_id, orders.payment_type, orders.amount, orders.status, orders.orderer_id, orders.message, orders.category, orders.anonymous, orders.source, orders.reference,
    orer.display_name AS orderer_display_name
FROM orders
    LEFT JOIN orderers orer ON orer.id = orders.orderer_id
    INNER JOIN game_note_orders ON game_note_orders.order_id = orders.id
    AND game_note_orders.game_note_id = $1::uuid
ORDER BY game_note_orders.created_at DESC
LIMIT $3::bigint OFFSET $2::bigint
`

type FindPaginatedOrdersByGameNoteIDParams struct {
	GameNoteID uuid.UUID `json:"game_note_id"`
	Offset     int64     `json:"offset"`
	Limit      int64     `json:"limit"`
}

type FindPaginatedOrdersByGameNoteIDRow struct {
	ID                 uuid.UUID       `json:"id"`
	CreatedAt          time.Time       `json:"created_at"`
	CreatedBy          *uuid.UUID      `json:"created_by"`
	UpdatedAt          time.Time       `json:"updated_at"`
	UpdatedBy          *uuid.UUID      `json:"updated_by"`
	ReceiverID         uuid.UUID       `json:"receiver_id"`
	PaymentType        int16           `json:"payment_type"`
	Amount             float32         `json:"amount"`
	Status             OrderStatus     `json:"status"`
	OrdererID          uuid.UUID       `json:"orderer_id"`
	Message            string          `json:"message"`
	Category           ContentCategory `json:"category"`
	Anonymous          bool            `json:"anonymous"`
	Source             string          `json:"source"`
	Reference          []byte          `json:"reference"`
	OrdererDisplayName *string         `json:"orderer_display_name"`
}

func (q *Queries) FindPaginatedOrdersByGameNoteID(ctx context.Context, arg FindPaginatedOrdersByGameNoteIDParams) ([]*FindPaginatedOrdersByGameNoteIDRow, error) {
	rows, err := q.db.Query(ctx, findPaginatedOrdersByGameNoteID, arg.GameNoteID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindPaginatedOrdersByGameNoteIDRow{}
	for rows.Next() {
		var i FindPaginatedOrdersByGameNoteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.ReceiverID,
			&i.PaymentType,
			&i.Amount,
			&i.Status,
			&i.OrdererID,
			&i.Message,
			&i.Category,
			&i.Anonymous,
			&i.Source,
			&i.Reference,
			&i.OrdererDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPaginatedOrdersByMovieNoteID = `-- name: FindPaginatedOrdersByMovieNoteID :many
SELECT orders.id, orders.created_at, orders.created_by, orders.updated_at, orders.updated_by, orders.receiver_id, orders.payment_type, orders.amount, orders.status, orders.orderer_id, orders.message, orders.category, orders.anonymous, orders.source, orders.reference,
    orer.display_name AS orderer_display_name
FROM orders
    LEFT JOIN orderers orer ON orer.id = orders.orderer_id
    INNER JOIN movie_note_orders ON movie_note_orders.order_id = orders.id
    AND movie_note_orders.movie_note_id = $1::uuid
ORDER BY movie_note_orders.created_at DESC
LIMIT $3::bigint OFFSET $2::bigint
`

type FindPaginatedOrdersByMovieNoteIDParams struct {
	MovieNoteID uuid.UUID `json:"movie_note_id"`
	Offset      int64     `json:"offset"`
	Limit       int64     `json:"limit"`
}

type FindPaginatedOrdersByMovieNoteIDRow struct {
	ID                 uuid.UUID       `json:"id"`
	CreatedAt          time.Time       `json:"created_at"`
	CreatedBy          *uuid.UUID      `json:"created_by"`
	UpdatedAt          time.Time       `json:"updated_at"`
	UpdatedBy          *uuid.UUID      `json:"updated_by"`
	ReceiverID         uuid.UUID       `json:"receiver_id"`
	PaymentType        int16           `json:"payment_type"`
	Amount             float32         `json:"amount"`
	Status             OrderStatus     `json:"status"`
	OrdererID          uuid.UUID       `json:"orderer_id"`
	Message            string          `json:"message"`
	Category           ContentCategory `json:"category"`
	Anonymous          bool            `json:"anonymous"`
	Source             string          `json:"source"`
	Reference          []byte          `json:"reference"`
	OrdererDisplayName *string         `json:"orderer_display_name"`
}

func (q *Queries) FindPaginatedOrdersByMovieNoteID(ctx context.Context, arg FindPaginatedOrdersByMovieNoteIDParams) ([]*FindPaginatedOrdersByMovieNoteIDRow, error) {
	rows, err := q.db.Query(ctx, findPaginatedOrdersByMovieNoteID, arg.MovieNoteID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindPaginatedOrdersByMovieNoteIDRow{}
	for rows.Next() {
		var i FindPaginatedOrdersByMovieNoteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.ReceiverID,
			&i.PaymentType,
			&i.Amount,
			&i.Status,
			&i.OrdererID,
			&i.Message,
			&i.Category,
			&i.Anonymous,
			&i.Source,
			&i.Reference,
			&i.OrdererDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (
        created_by,
        updated_by,
        receiver_id,
        payment_type,
        amount,
        status,
        orderer_id,
        category,
        message,
        source,
        reference,
        anonymous
    )
VALUES (
        $1::uuid,
        $2::uuid,
        $3::uuid,
        $4::smallint,
        $5::real,
        $6::order_status,
        $7::uuid,
        $8::content_category,
        $9::text,
        $10::text,
        $11::jsonb,
        $12::boolean
    )
RETURNING id, created_at, created_by, updated_at, updated_by, receiver_id, payment_type, amount, status, orderer_id, message, category, anonymous, source, reference
`

type InsertOrderParams struct {
	CreatedBy   *uuid.UUID      `json:"created_by"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
	ReceiverID  uuid.UUID       `json:"receiver_id"`
	PaymentType int16           `json:"payment_type"`
	Amount      float32         `json:"amount"`
	Status      OrderStatus     `json:"status"`
	OrdererID   uuid.UUID       `json:"orderer_id"`
	Category    ContentCategory `json:"category"`
	Message     string          `json:"message"`
	Source      string          `json:"source"`
	Reference   []byte          `json:"reference"`
	Anonymous   bool            `json:"anonymous"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (*Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.ReceiverID,
		arg.PaymentType,
		arg.Amount,
		arg.Status,
		arg.OrdererID,
		arg.Category,
		arg.Message,
		arg.Source,
		arg.Reference,
		arg.Anonymous,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.ReceiverID,
		&i.PaymentType,
		&i.Amount,
		&i.Status,
		&i.OrdererID,
		&i.Message,
		&i.Category,
		&i.Anonymous,
		&i.Source,
		&i.Reference,
	)
	return &i, err
}

const updateOrderByID = `-- name: UpdateOrderByID :one
UPDATE orders
SET updated_at = now(),
    updated_by = $1::uuid,
    status = $2::order_status
WHERE id = $3::uuid
RETURNING id, created_at, created_by, updated_at, updated_by, receiver_id, payment_type, amount, status, orderer_id, message, category, anonymous, source, reference
`

type UpdateOrderByIDParams struct {
	UpdatedBy uuid.UUID   `json:"updated_by"`
	Status    OrderStatus `json:"status"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateOrderByID(ctx context.Context, arg UpdateOrderByIDParams) (*Order, error) {
	row := q.db.QueryRow(ctx, updateOrderByID, arg.UpdatedBy, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.ReceiverID,
		&i.PaymentType,
		&i.Amount,
		&i.Status,
		&i.OrdererID,
		&i.Message,
		&i.Category,
		&i.Anonymous,
		&i.Source,
		&i.Reference,
	)
	return &i, err
}
