// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orderer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findOrdererByID = `-- name: FindOrdererByID :one
SELECT id, created_at, created_by, updated_at, updated_by, user_id, username, anonymous FROM "orderers" WHERE "id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindOrdererByID(ctx context.Context, id uuid.UUID) (*Orderer, error) {
	row := q.db.QueryRow(ctx, findOrdererByID, id)
	var i Orderer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.Username,
		&i.Anonymous,
	)
	return &i, err
}

const findOrdererByUserID = `-- name: FindOrdererByUserID :one
SELECT id, created_at, created_by, updated_at, updated_by, user_id, username, anonymous FROM "orderers" WHERE "user_id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindOrdererByUserID(ctx context.Context, userID *uuid.UUID) (*Orderer, error) {
	row := q.db.QueryRow(ctx, findOrdererByUserID, userID)
	var i Orderer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.Username,
		&i.Anonymous,
	)
	return &i, err
}

const insertOrderer = `-- name: InsertOrderer :one
INSERT INTO "orderers" (
    "created_by",
    "updated_by",
    "user_id",
    "username",
    "anonymous"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, created_by, updated_at, updated_by, user_id, username, anonymous
`

type InsertOrdererParams struct {
	CreatedBy *uuid.UUID `json:"created_by"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	UserID    *uuid.UUID `json:"user_id"`
	Username  string     `json:"username"`
	Anonymous bool       `json:"anonymous"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertOrderer(ctx context.Context, arg InsertOrdererParams) (*Orderer, error) {
	row := q.db.QueryRow(ctx, insertOrderer,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.UserID,
		arg.Username,
		arg.Anonymous,
	)
	var i Orderer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UserID,
		&i.Username,
		&i.Anonymous,
	)
	return &i, err
}

const updateOrdererByUserID = `-- name: UpdateOrdererByUserID :exec
UPDATE "orderers"
SET "updated_at" = now(),
    "updated_by" = $2,
    "username" = $3
WHERE "user_id" = $1
`

type UpdateOrdererByUserIDParams struct {
	UserID    *uuid.UUID `json:"user_id"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	Username  string     `json:"username"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) UpdateOrdererByUserID(ctx context.Context, arg UpdateOrdererByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateOrdererByUserID, arg.UserID, arg.UpdatedBy, arg.Username)
	return err
}
