// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: poster_previews.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePosterPreview = `-- name: DeletePosterPreview :exec
DELETE FROM "poster_previews" WHERE "id" = $1
`

func (q *Queries) DeletePosterPreview(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePosterPreview, id)
	return err
}

const findPosterPreviewByCreatedAtAfterAndCreatedBy = `-- name: FindPosterPreviewByCreatedAtAfterAndCreatedBy :many
SELECT id, created_at, created_by, object_key 
FROM "poster_previews" 
WHERE "created_at" > $1 
    AND "created_by" = $2
ORDER BY "created_at" DESC
LIMIT 5
`

type FindPosterPreviewByCreatedAtAfterAndCreatedByParams struct {
	CreatedAt time.Time `json:"created_at"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) FindPosterPreviewByCreatedAtAfterAndCreatedBy(ctx context.Context, arg FindPosterPreviewByCreatedAtAfterAndCreatedByParams) ([]*PosterPreview, error) {
	rows, err := q.db.Query(ctx, findPosterPreviewByCreatedAtAfterAndCreatedBy, arg.CreatedAt, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PosterPreview
	for rows.Next() {
		var i PosterPreview
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPosterPreviewByCreatedBy = `-- name: FindPosterPreviewByCreatedBy :many
SELECT id, created_at, created_by, object_key 
FROM "poster_previews" 
WHERE "created_by" = $1
ORDER BY "created_at" DESC
`

func (q *Queries) FindPosterPreviewByCreatedBy(ctx context.Context, createdBy uuid.UUID) ([]*PosterPreview, error) {
	rows, err := q.db.Query(ctx, findPosterPreviewByCreatedBy, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PosterPreview
	for rows.Next() {
		var i PosterPreview
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPosterPreviewById = `-- name: FindPosterPreviewById :one
SELECT id, created_at, created_by, object_key FROM "poster_previews" WHERE "id" = $1
`

func (q *Queries) FindPosterPreviewById(ctx context.Context, id uuid.UUID) (*PosterPreview, error) {
	row := q.db.QueryRow(ctx, findPosterPreviewById, id)
	var i PosterPreview
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ObjectKey,
	)
	return &i, err
}

const insertPosterPreview = `-- name: InsertPosterPreview :one
INSERT INTO "poster_previews" (
    "id",
    "created_by",
    "object_key"
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, created_at, created_by, object_key
`

type InsertPosterPreviewParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedBy uuid.UUID `json:"created_by"`
	ObjectKey string    `json:"object_key"`
}

func (q *Queries) InsertPosterPreview(ctx context.Context, arg InsertPosterPreviewParams) (*PosterPreview, error) {
	row := q.db.QueryRow(ctx, insertPosterPreview, arg.ID, arg.CreatedBy, arg.ObjectKey)
	var i PosterPreview
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ObjectKey,
	)
	return &i, err
}
