// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findProfileById = `-- name: FindProfileById :one
SELECT user_id, created_at, updated_at, updated_by, username, link, description, avatar_url, avatar_preview_key
FROM "profiles"
WHERE "user_id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindProfileById(ctx context.Context, userID uuid.UUID) (*Profile, error) {
	row := q.db.QueryRow(ctx, findProfileById, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Username,
		&i.Link,
		&i.Description,
		&i.AvatarUrl,
		&i.AvatarPreviewKey,
	)
	return &i, err
}

const findProfileByLink = `-- name: FindProfileByLink :one
SELECT user_id, created_at, updated_at, updated_by, username, link, description, avatar_url, avatar_preview_key
FROM "profiles"
WHERE "link" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindProfileByLink(ctx context.Context, link string) (*Profile, error) {
	row := q.db.QueryRow(ctx, findProfileByLink, link)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Username,
		&i.Link,
		&i.Description,
		&i.AvatarUrl,
		&i.AvatarPreviewKey,
	)
	return &i, err
}

const insertProfile = `-- name: InsertProfile :one
INSERT INTO "profiles" (
        "user_id",
        "username",
        "link",
        "description",
        "avatar_url",
        "avatar_preview_key"
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, created_at, updated_at, updated_by, username, link, description, avatar_url, avatar_preview_key
`

type InsertProfileParams struct {
	UserID           uuid.UUID `json:"user_id"`
	Username         string    `json:"username"`
	Link             string    `json:"link"`
	Description      string    `json:"description"`
	AvatarUrl        *string   `json:"avatar_url"`
	AvatarPreviewKey *string   `json:"avatar_preview_key"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (*Profile, error) {
	row := q.db.QueryRow(ctx, insertProfile,
		arg.UserID,
		arg.Username,
		arg.Link,
		arg.Description,
		arg.AvatarUrl,
		arg.AvatarPreviewKey,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Username,
		&i.Link,
		&i.Description,
		&i.AvatarUrl,
		&i.AvatarPreviewKey,
	)
	return &i, err
}

const updateProfileByUserId = `-- name: UpdateProfileByUserId :one
UPDATE "profiles"
SET "updated_at" = now(),
    "updated_by" = $2,
    "username" = $3,
    "link" = $4,
    "description" = $5,
    "avatar_url" = $6,
    "avatar_preview_key" = $7
WHERE "user_id" = $1
RETURNING user_id, created_at, updated_at, updated_by, username, link, description, avatar_url, avatar_preview_key
`

type UpdateProfileByUserIdParams struct {
	UserID           uuid.UUID  `json:"user_id"`
	UpdatedBy        *uuid.UUID `json:"updated_by"`
	Username         string     `json:"username"`
	Link             string     `json:"link"`
	Description      string     `json:"description"`
	AvatarUrl        *string    `json:"avatar_url"`
	AvatarPreviewKey *string    `json:"avatar_preview_key"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) UpdateProfileByUserId(ctx context.Context, arg UpdateProfileByUserIdParams) (*Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileByUserId,
		arg.UserID,
		arg.UpdatedBy,
		arg.Username,
		arg.Link,
		arg.Description,
		arg.AvatarUrl,
		arg.AvatarPreviewKey,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Username,
		&i.Link,
		&i.Description,
		&i.AvatarUrl,
		&i.AvatarPreviewKey,
	)
	return &i, err
}

const updateProfilePreviewAvatarByUserId = `-- name: UpdateProfilePreviewAvatarByUserId :exec
UPDATE "profiles"
SET "updated_at" = now(),
    "updated_by" = $2,
    "avatar_preview_key" = $3
WHERE "user_id" = $1
`

type UpdateProfilePreviewAvatarByUserIdParams struct {
	UserID           uuid.UUID  `json:"user_id"`
	UpdatedBy        *uuid.UUID `json:"updated_by"`
	AvatarPreviewKey *string    `json:"avatar_preview_key"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) UpdateProfilePreviewAvatarByUserId(ctx context.Context, arg UpdateProfilePreviewAvatarByUserIdParams) error {
	_, err := q.db.Exec(ctx, updateProfilePreviewAvatarByUserId, arg.UserID, arg.UpdatedBy, arg.AvatarPreviewKey)
	return err
}
