// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findProfileById = `-- name: FindProfileById :one
SELECT user_id, created_at, updated_at, updated_by, username, link, description
FROM "profiles"
WHERE "user_id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindProfileById(ctx context.Context, userID uuid.UUID) (*Profile, error) {
	row := q.db.QueryRow(ctx, findProfileById, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Username,
		&i.Link,
		&i.Description,
	)
	return &i, err
}

const findProfileByLink = `-- name: FindProfileByLink :one
SELECT user_id, created_at, updated_at, updated_by, username, link, description
FROM "profiles"
WHERE "link" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindProfileByLink(ctx context.Context, link string) (*Profile, error) {
	row := q.db.QueryRow(ctx, findProfileByLink, link)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Username,
		&i.Link,
		&i.Description,
	)
	return &i, err
}

const getUserFollows = `-- name: GetUserFollows :many
SELECT p.user_id, p.created_at, p.updated_at, p.updated_by, p.username, p.link, p.description 
FROM "profiles" p
JOIN "followers" f ON p."user_id" = f."user_id"
WHERE f."follower_id" = $1
ORDER BY f."created_at" DESC
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) GetUserFollows(ctx context.Context, followerID uuid.UUID) ([]*Profile, error) {
	rows, err := q.db.Query(ctx, getUserFollows, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Username,
			&i.Link,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProfile = `-- name: InsertProfile :one
INSERT INTO "profiles" (
        "user_id",
        "username",
        "link",
        "description"
    )
VALUES ($1, $2, $3, $4)
RETURNING user_id, created_at, updated_at, updated_by, username, link, description
`

type InsertProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Username    string    `json:"username"`
	Link        string    `json:"link"`
	Description string    `json:"description"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (*Profile, error) {
	row := q.db.QueryRow(ctx, insertProfile,
		arg.UserID,
		arg.Username,
		arg.Link,
		arg.Description,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Username,
		&i.Link,
		&i.Description,
	)
	return &i, err
}

const updateProfileByUserId = `-- name: UpdateProfileByUserId :one
UPDATE "profiles"
SET "updated_at" = now(),
    "updated_by" = $2,
    "username" = $3,
    "link" = $4,
    "description" = $5
WHERE "user_id" = $1
RETURNING user_id, created_at, updated_at, updated_by, username, link, description
`

type UpdateProfileByUserIdParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
	Username    string     `json:"username"`
	Link        string     `json:"link"`
	Description string     `json:"description"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) UpdateProfileByUserId(ctx context.Context, arg UpdateProfileByUserIdParams) (*Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileByUserId,
		arg.UserID,
		arg.UpdatedBy,
		arg.Username,
		arg.Link,
		arg.Description,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Username,
		&i.Link,
		&i.Description,
	)
	return &i, err
}
