// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findProfileById = `-- name: FindProfileById :one
SELECT user_id, created_at, updated_at, username, link FROM "profiles" WHERE "user_id" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindProfileById(ctx context.Context, userID uuid.UUID) (*Profile, error) {
	row := q.db.QueryRow(ctx, findProfileById, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Link,
	)
	return &i, err
}

const findProfileByLink = `-- name: FindProfileByLink :one
SELECT user_id, created_at, updated_at, username, link FROM "profiles" WHERE "link" = $1
`

// Author: Egor Kuzmin (keelfy)
func (q *Queries) FindProfileByLink(ctx context.Context, link string) (*Profile, error) {
	row := q.db.QueryRow(ctx, findProfileByLink, link)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Link,
	)
	return &i, err
}

const insertProfile = `-- name: InsertProfile :one
INSERT INTO "profiles" (
    "user_id", 
    "username", 
    "link"
) VALUES (
    $1,
    $2,
    $3
)
RETURNING user_id, created_at, updated_at, username, link
`

type InsertProfileParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Username string    `json:"username"`
	Link     string    `json:"link"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (*Profile, error) {
	row := q.db.QueryRow(ctx, insertProfile, arg.UserID, arg.Username, arg.Link)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Link,
	)
	return &i, err
}

const updateProfileByUserId = `-- name: UpdateProfileByUserId :one
UPDATE "profiles" SET
    "username" = $2,
    "link" = $3
WHERE "user_id" = $1
RETURNING user_id, created_at, updated_at, username, link
`

type UpdateProfileByUserIdParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Username string    `json:"username"`
	Link     string    `json:"link"`
}

// Author: Egor Kuzmin (keelfy)
func (q *Queries) UpdateProfileByUserId(ctx context.Context, arg UpdateProfileByUserIdParams) (*Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileByUserId, arg.UserID, arg.Username, arg.Link)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Link,
	)
	return &i, err
}
