// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: profile_avatars.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findProfileAvatarByUserId = `-- name: FindProfileAvatarByUserId :one
SELECT user_id, created_at, created_by, updated_at, updated_by, avatar_key, avatar_url, avatar_preview_key
FROM profile_avatars
WHERE user_id = $1::uuid
`

func (q *Queries) FindProfileAvatarByUserId(ctx context.Context, userID uuid.UUID) (*ProfileAvatar, error) {
	row := q.db.QueryRow(ctx, findProfileAvatarByUserId, userID)
	var i ProfileAvatar
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.AvatarKey,
		&i.AvatarUrl,
		&i.AvatarPreviewKey,
	)
	return &i, err
}

const insertProfileAvatar = `-- name: InsertProfileAvatar :one
INSERT INTO profile_avatars (
        user_id,
        created_by,
        updated_by,
        avatar_key,
        avatar_url,
        avatar_preview_key
    )
VALUES (
        $1::uuid,
        $2::uuid,
        $3::uuid,
        $4::text,
        $5::text,
        $6::text
    )
RETURNING user_id, created_at, created_by, updated_at, updated_by, avatar_key, avatar_url, avatar_preview_key
`

type InsertProfileAvatarParams struct {
	UserID           uuid.UUID  `json:"user_id"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	UpdatedBy        *uuid.UUID `json:"updated_by"`
	AvatarKey        *string    `json:"avatar_key"`
	AvatarUrl        *string    `json:"avatar_url"`
	AvatarPreviewKey *string    `json:"avatar_preview_key"`
}

func (q *Queries) InsertProfileAvatar(ctx context.Context, arg InsertProfileAvatarParams) (*ProfileAvatar, error) {
	row := q.db.QueryRow(ctx, insertProfileAvatar,
		arg.UserID,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.AvatarKey,
		arg.AvatarUrl,
		arg.AvatarPreviewKey,
	)
	var i ProfileAvatar
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.AvatarKey,
		&i.AvatarUrl,
		&i.AvatarPreviewKey,
	)
	return &i, err
}

const updateProfileAvatarByUserId = `-- name: UpdateProfileAvatarByUserId :one
UPDATE profile_avatars
SET updated_at = now(),
    updated_by = $1::uuid,
    avatar_key = $2::text,
    avatar_url = $3::text,
    avatar_preview_key = $4::text
WHERE user_id = $5::uuid
RETURNING user_id, created_at, created_by, updated_at, updated_by, avatar_key, avatar_url, avatar_preview_key
`

type UpdateProfileAvatarByUserIdParams struct {
	UpdatedBy        *uuid.UUID `json:"updated_by"`
	AvatarKey        *string    `json:"avatar_key"`
	AvatarUrl        *string    `json:"avatar_url"`
	AvatarPreviewKey *string    `json:"avatar_preview_key"`
	UserID           uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateProfileAvatarByUserId(ctx context.Context, arg UpdateProfileAvatarByUserIdParams) (*ProfileAvatar, error) {
	row := q.db.QueryRow(ctx, updateProfileAvatarByUserId,
		arg.UpdatedBy,
		arg.AvatarKey,
		arg.AvatarUrl,
		arg.AvatarPreviewKey,
		arg.UserID,
	)
	var i ProfileAvatar
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.AvatarKey,
		&i.AvatarUrl,
		&i.AvatarPreviewKey,
	)
	return &i, err
}
