// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddGameNoteReaction(ctx context.Context, arg AddGameNoteReactionParams) error
	// Author: Egor Kuzmin (keelfy)
	CountFollowers(ctx context.Context, userID uuid.UUID) (int64, error)
	// Author: Egor Kuzmin (keelfy)
	CountOrdersByGameNoteId(ctx context.Context, gameNoteID uuid.UUID) (int64, error)
	// Author: Egor Kuzmin (keelfy)
	// Counts orders by receiver id
	CountOrdersByReceiverId(ctx context.Context, receiverID uuid.UUID) (int64, error)
	// Author: Egor Kuzmin (keelfy)
	CountPlayedGameNotesByUserId(ctx context.Context, userID uuid.UUID) (int64, error)
	// Author: Egor Kuzmin (keelfy)
	DeleteFollower(ctx context.Context, arg DeleteFollowerParams) error
	// Author: Egor Kuzmin (keelfy)
	DeleteGameNoteById(ctx context.Context, id uuid.UUID) error
	DeletePosterPreview(ctx context.Context, id uuid.UUID) error
	FindElasticsearchMigrationByName(ctx context.Context, name string) (*EsMigrationLog, error)
	// Author: Egor Kuzmin (keelfy)
	FindGameNoteById(ctx context.Context, id uuid.UUID) (*GameNote, error)
	// Author: Egor Kuzmin (keelfy)
	// Queries last orders by receiver id
	FindLastOrdersByReceiverId(ctx context.Context, arg FindLastOrdersByReceiverIdParams) ([]*FindLastOrdersByReceiverIdRow, error)
	// Author: Egor Kuzmin (keelfy)
	// Queries order by id
	FindOrderById(ctx context.Context, id uuid.UUID) (*Order, error)
	// Author: Egor Kuzmin (keelfy)
	FindOrdererById(ctx context.Context, id uuid.UUID) (*Orderer, error)
	// Author: Egor Kuzmin (keelfy)
	FindOrdererByUserId(ctx context.Context, userID *uuid.UUID) (*Orderer, error)
	// Author: Egor Kuzmin (keelfy)
	// Queries orders by receiver id
	FindOrdersByReceiverId(ctx context.Context, receiverID uuid.UUID) ([]*Order, error)
	// Author: Egor Kuzmin (keelfy)
	FindPaginatedGameNotesByUserId(ctx context.Context, arg FindPaginatedGameNotesByUserIdParams) ([]*FindPaginatedGameNotesByUserIdRow, error)
	// Author: Egor Kuzmin (keelfy)
	FindPaginatedOrdersByGameNoteId(ctx context.Context, arg FindPaginatedOrdersByGameNoteIdParams) ([]*Order, error)
	FindPosterPreviewByCreatedAtAfterAndCreatedBy(ctx context.Context, arg FindPosterPreviewByCreatedAtAfterAndCreatedByParams) ([]*PosterPreview, error)
	FindPosterPreviewByCreatedBy(ctx context.Context, createdBy uuid.UUID) ([]*PosterPreview, error)
	FindPosterPreviewById(ctx context.Context, id uuid.UUID) (*PosterPreview, error)
	// Author: Egor Kuzmin (keelfy)
	FindProfileAvatarByUserId(ctx context.Context, userID uuid.UUID) (*ProfileAvatar, error)
	// Author: Egor Kuzmin (keelfy)
	FindProfileById(ctx context.Context, userID uuid.UUID) (*Profile, error)
	// Author: Egor Kuzmin (keelfy)
	FindProfileByLink(ctx context.Context, link string) (*Profile, error)
	GetGameNoteReactionsByGameNoteId(ctx context.Context, gameNoteID uuid.UUID) ([]*GetGameNoteReactionsByGameNoteIdRow, error)
	GetGameNoteReactionsByGameNoteIdAndUserId(ctx context.Context, arg GetGameNoteReactionsByGameNoteIdAndUserIdParams) ([]*GetGameNoteReactionsByGameNoteIdAndUserIdRow, error)
	// Author: Egor Kuzmin (keelfy)
	GetUserFollows(ctx context.Context, followerID uuid.UUID) ([]*Profile, error)
	InsertElasticsearchMigration(ctx context.Context, name string) error
	// Author: Egor Kuzmin (keelfy)
	InsertFollower(ctx context.Context, arg InsertFollowerParams) error
	// Author: Egor Kuzmin (keelfy)
	InsertGameNote(ctx context.Context, arg InsertGameNoteParams) (*GameNote, error)
	// Author: Egor Kuzmin (keelfy)
	InsertGameNoteOrder(ctx context.Context, arg InsertGameNoteOrderParams) (*GameNoteOrder, error)
	// Author: Egor Kuzmin (keelfy)
	// Inserts a new order
	InsertOrder(ctx context.Context, arg InsertOrderParams) (*Order, error)
	// Author: Egor Kuzmin (keelfy)
	InsertOrderer(ctx context.Context, arg InsertOrdererParams) (*Orderer, error)
	InsertPosterPreview(ctx context.Context, arg InsertPosterPreviewParams) (*PosterPreview, error)
	// Author: Egor Kuzmin (keelfy)
	InsertProfile(ctx context.Context, arg InsertProfileParams) (*Profile, error)
	// Author: Egor Kuzmin (keelfy)
	InsertProfileAvatar(ctx context.Context, arg InsertProfileAvatarParams) (*ProfileAvatar, error)
	// Author: Egor Kuzmin (keelfy)
	IsFollowing(ctx context.Context, arg IsFollowingParams) (int64, error)
	RemoveGameNoteReaction(ctx context.Context, arg RemoveGameNoteReactionParams) error
	// Author: Egor Kuzmin (keelfy)
	ResetApprovedOrdersByGameNoteId(ctx context.Context, gameNoteID uuid.UUID) error
	// Author: Egor Kuzmin (keelfy)
	UpdateGameNoteById(ctx context.Context, arg UpdateGameNoteByIdParams) error
	// Author: Egor Kuzmin (keelfy)
	// Updates order, updated_at and updated_by
	UpdateOrderById(ctx context.Context, arg UpdateOrderByIdParams) (*Order, error)
	// Author: Egor Kuzmin (keelfy)
	UpdateOrdererByUserId(ctx context.Context, arg UpdateOrdererByUserIdParams) (*Orderer, error)
	// Author: Egor Kuzmin (keelfy)
	UpdateProfileAvatarByUserId(ctx context.Context, arg UpdateProfileAvatarByUserIdParams) (*ProfileAvatar, error)
	// Author: Egor Kuzmin (keelfy)
	UpdateProfileByUserId(ctx context.Context, arg UpdateProfileByUserIdParams) (*Profile, error)
}

var _ Querier = (*Queries)(nil)
