// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tmdb_sync_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeTMDBSync = `-- name: CompleteTMDBSync :exec
UPDATE tmdb_sync_logs
SET status = 'completed',
    completed_at = now(),
    movies_processed = $1::bigint
WHERE id = $2
`

type CompleteTMDBSyncParams struct {
	MoviesProcessed int64     `json:"movies_processed"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) CompleteTMDBSync(ctx context.Context, arg CompleteTMDBSyncParams) error {
	_, err := q.db.Exec(ctx, completeTMDBSync, arg.MoviesProcessed, arg.ID)
	return err
}

const completeTMDBSyncWithError = `-- name: CompleteTMDBSyncWithError :exec
UPDATE tmdb_sync_logs
SET status = 'failed',
    completed_at = now(),
    error_message = $1::text
WHERE id = $2
`

type CompleteTMDBSyncWithErrorParams struct {
	ErrorMessage string    `json:"error_message"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) CompleteTMDBSyncWithError(ctx context.Context, arg CompleteTMDBSyncWithErrorParams) error {
	_, err := q.db.Exec(ctx, completeTMDBSyncWithError, arg.ErrorMessage, arg.ID)
	return err
}

const createTMDBSync = `-- name: CreateTMDBSync :one
INSERT INTO tmdb_sync_logs (sync_type, started_at, status)
VALUES (
        $1::igdb_sync_type,
        now(),
        'pending'
    )
RETURNING id, sync_type, status, started_at, movies_processed, completed_at, error_message
`

func (q *Queries) CreateTMDBSync(ctx context.Context, syncType IgdbSyncType) (*TmdbSyncLog, error) {
	row := q.db.QueryRow(ctx, createTMDBSync, syncType)
	var i TmdbSyncLog
	err := row.Scan(
		&i.ID,
		&i.SyncType,
		&i.Status,
		&i.StartedAt,
		&i.MoviesProcessed,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return &i, err
}

const getLastSuccessfulTMDBsync = `-- name: GetLastSuccessfulTMDBsync :one
SELECT id, sync_type, status, started_at, movies_processed, completed_at, error_message
FROM tmdb_sync_logs
WHERE sync_type = $1::igdb_sync_type
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLastSuccessfulTMDBsync(ctx context.Context, syncType IgdbSyncType) (*TmdbSyncLog, error) {
	row := q.db.QueryRow(ctx, getLastSuccessfulTMDBsync, syncType)
	var i TmdbSyncLog
	err := row.Scan(
		&i.ID,
		&i.SyncType,
		&i.Status,
		&i.StartedAt,
		&i.MoviesProcessed,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return &i, err
}

const startTMDBSync = `-- name: StartTMDBSync :exec
UPDATE tmdb_sync_logs
SET status = 'in_progress'
WHERE id = $1
`

func (q *Queries) StartTMDBSync(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startTMDBSync, id)
	return err
}
