// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tracked_rewards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteTrackedRewardsByBroadcasterID = `-- name: DeleteTrackedRewardsByBroadcasterID :exec
DELETE FROM broadcaster_tracked_rewards
WHERE broadcaster_id = $1::text
    AND tracked_reward_id = ANY($2::text[])
`

type DeleteTrackedRewardsByBroadcasterIDParams struct {
	BroadcasterID    string   `json:"broadcaster_id"`
	TrackedRewardIds []string `json:"tracked_reward_ids"`
}

func (q *Queries) DeleteTrackedRewardsByBroadcasterID(ctx context.Context, arg DeleteTrackedRewardsByBroadcasterIDParams) error {
	_, err := q.db.Exec(ctx, deleteTrackedRewardsByBroadcasterID, arg.BroadcasterID, arg.TrackedRewardIds)
	return err
}

const findTrackedRewardsByBroadcasterID = `-- name: FindTrackedRewardsByBroadcasterID :many
SELECT broadcaster_id, tracked_reward_id, category, created_at, updated_at, updated_by
FROM broadcaster_tracked_rewards
WHERE broadcaster_id = $1::text
`

func (q *Queries) FindTrackedRewardsByBroadcasterID(ctx context.Context, broadcasterID string) ([]*BroadcasterTrackedReward, error) {
	rows, err := q.db.Query(ctx, findTrackedRewardsByBroadcasterID, broadcasterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*BroadcasterTrackedReward{}
	for rows.Next() {
		var i BroadcasterTrackedReward
		if err := rows.Scan(
			&i.BroadcasterID,
			&i.TrackedRewardID,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrackedReward = `-- name: InsertTrackedReward :exec
INSERT INTO broadcaster_tracked_rewards (
        broadcaster_id,
        tracked_reward_id,
        category,
        updated_by
    )
VALUES (
        $1::text,
        $2::text,
        $3::text,
        $4::uuid
    ) ON CONFLICT (broadcaster_id, tracked_reward_id) DO
UPDATE
SET category = $3::text,
    updated_by = $4::uuid
`

type InsertTrackedRewardParams struct {
	BroadcasterID   string    `json:"broadcaster_id"`
	TrackedRewardID string    `json:"tracked_reward_id"`
	Category        string    `json:"category"`
	UpdatedBy       uuid.UUID `json:"updated_by"`
}

func (q *Queries) InsertTrackedReward(ctx context.Context, arg InsertTrackedRewardParams) error {
	_, err := q.db.Exec(ctx, insertTrackedReward,
		arg.BroadcasterID,
		arg.TrackedRewardID,
		arg.Category,
		arg.UpdatedBy,
	)
	return err
}
