// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: twitch_connections.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTwitchConnection = `-- name: CreateTwitchConnection :exec
INSERT INTO twitch_connections (
        owner_id,
        broadcaster_id,
        login,
        access_token,
        refresh_token,
        expires_at
    )
VALUES (
        $1::uuid,
        $2::text,
        $3::text,
        $4::text,
        $5::text,
        $6::timestamptz
    ) ON CONFLICT (broadcaster_id) DO
UPDATE
SET owner_id = $1::uuid,
    login = $3::text,
    access_token = $4::text,
    refresh_token = $5::text,
    expires_at = $6::timestamptz
`

type CreateTwitchConnectionParams struct {
	OwnerID       uuid.UUID `json:"owner_id"`
	BroadcasterID string    `json:"broadcaster_id"`
	Login         string    `json:"login"`
	AccessToken   string    `json:"access_token"`
	RefreshToken  string    `json:"refresh_token"`
	ExpiresAt     time.Time `json:"expires_at"`
}

func (q *Queries) CreateTwitchConnection(ctx context.Context, arg CreateTwitchConnectionParams) error {
	_, err := q.db.Exec(ctx, createTwitchConnection,
		arg.OwnerID,
		arg.BroadcasterID,
		arg.Login,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}

const getTwitchConnectionByOwnerID = `-- name: GetTwitchConnectionByOwnerID :one
SELECT "login"
FROM twitch_connections
WHERE owner_id = $1::uuid
`

func (q *Queries) GetTwitchConnectionByOwnerID(ctx context.Context, ownerID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTwitchConnectionByOwnerID, ownerID)
	var login string
	err := row.Scan(&login)
	return login, err
}
