// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: websocket_connections.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findAvailableWebsocketConnectionsToSubscribe = `-- name: FindAvailableWebsocketConnectionsToSubscribe :many
SELECT wc.id, wc.session_id, wc.created_at, wc.updated_at, wc.last_ping, wc.status, wc.error_count, wc.error_message, wc.subscription_count, wc.identity_id,
    100 - subscription_count AS free_slots
FROM websocket_connections wc
WHERE wc.status = 'active'
    AND wc.session_id IS NOT NULL
    AND wc.session_id != ''
    AND wc.subscription_count < 100 FOR
UPDATE
`

type FindAvailableWebsocketConnectionsToSubscribeRow struct {
	ID                uuid.UUID `json:"id"`
	SessionID         *string   `json:"session_id"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	LastPing          time.Time `json:"last_ping"`
	Status            string    `json:"status"`
	ErrorCount        int32     `json:"error_count"`
	ErrorMessage      string    `json:"error_message"`
	SubscriptionCount int32     `json:"subscription_count"`
	IdentityID        uuid.UUID `json:"identity_id"`
	FreeSlots         int32     `json:"free_slots"`
}

func (q *Queries) FindAvailableWebsocketConnectionsToSubscribe(ctx context.Context) ([]*FindAvailableWebsocketConnectionsToSubscribeRow, error) {
	rows, err := q.db.Query(ctx, findAvailableWebsocketConnectionsToSubscribe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindAvailableWebsocketConnectionsToSubscribeRow{}
	for rows.Next() {
		var i FindAvailableWebsocketConnectionsToSubscribeRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPing,
			&i.Status,
			&i.ErrorCount,
			&i.ErrorMessage,
			&i.SubscriptionCount,
			&i.IdentityID,
			&i.FreeSlots,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWebsocketConnectionByID = `-- name: FindWebsocketConnectionByID :one
SELECT id, session_id, created_at, updated_at, last_ping, status, error_count, error_message, subscription_count, identity_id
FROM websocket_connections
WHERE id = $1::uuid
`

func (q *Queries) FindWebsocketConnectionByID(ctx context.Context, id uuid.UUID) (*WebsocketConnection, error) {
	row := q.db.QueryRow(ctx, findWebsocketConnectionByID, id)
	var i WebsocketConnection
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPing,
		&i.Status,
		&i.ErrorCount,
		&i.ErrorMessage,
		&i.SubscriptionCount,
		&i.IdentityID,
	)
	return &i, err
}

const findWebsocketConnectionsToRestore = `-- name: FindWebsocketConnectionsToRestore :many
SELECT id
FROM websocket_connections
WHERE status IN ('active', 'connecting')
    AND updated_at < NOW() - INTERVAL '5' MINUTE
`

func (q *Queries) FindWebsocketConnectionsToRestore(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findWebsocketConnectionsToRestore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWebsocketConnection = `-- name: InsertWebsocketConnection :one
INSERT INTO websocket_connections (id, status, identity_id)
VALUES ($1::uuid, $2::text, $3::uuid)
RETURNING id, session_id, created_at, updated_at, last_ping, status, error_count, error_message, subscription_count, identity_id
`

type InsertWebsocketConnectionParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	IdentityID uuid.UUID `json:"identity_id"`
}

func (q *Queries) InsertWebsocketConnection(ctx context.Context, arg InsertWebsocketConnectionParams) (*WebsocketConnection, error) {
	row := q.db.QueryRow(ctx, insertWebsocketConnection, arg.ID, arg.Status, arg.IdentityID)
	var i WebsocketConnection
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPing,
		&i.Status,
		&i.ErrorCount,
		&i.ErrorMessage,
		&i.SubscriptionCount,
		&i.IdentityID,
	)
	return &i, err
}

const updateWebsocketConnection = `-- name: UpdateWebsocketConnection :one
UPDATE websocket_connections
SET updated_at = NOW(),
    status = CASE
        WHEN $1::text != '' THEN $1::text
        ELSE status
    END,
    session_id = CASE
        WHEN $2::text != '' THEN $2::text
        ELSE session_id
    END,
    last_ping = CASE
        WHEN $3::timestamptz != to_timestamp(0) THEN $3::timestamptz
        ELSE last_ping
    END,
    error_count = CASE
        WHEN $4::int != 0 THEN $4::int
        ELSE error_count
    END,
    error_message = CASE
        WHEN $5::text != '' THEN $5::text
        ELSE error_message
    END
WHERE id = $6::uuid
RETURNING id, session_id, created_at, updated_at, last_ping, status, error_count, error_message, subscription_count, identity_id
`

type UpdateWebsocketConnectionParams struct {
	Status       string    `json:"status"`
	SessionID    string    `json:"session_id"`
	LastPing     time.Time `json:"last_ping"`
	ErrorCount   int32     `json:"error_count"`
	ErrorMessage string    `json:"error_message"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateWebsocketConnection(ctx context.Context, arg UpdateWebsocketConnectionParams) (*WebsocketConnection, error) {
	row := q.db.QueryRow(ctx, updateWebsocketConnection,
		arg.Status,
		arg.SessionID,
		arg.LastPing,
		arg.ErrorCount,
		arg.ErrorMessage,
		arg.ID,
	)
	var i WebsocketConnection
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPing,
		&i.Status,
		&i.ErrorCount,
		&i.ErrorMessage,
		&i.SubscriptionCount,
		&i.IdentityID,
	)
	return &i, err
}

const updateWebsocketConnectionStatus = `-- name: UpdateWebsocketConnectionStatus :exec
UPDATE websocket_connections
SET status = $1::text,
    updated_at = NOW()
WHERE id = $2::uuid
`

type UpdateWebsocketConnectionStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateWebsocketConnectionStatus(ctx context.Context, arg UpdateWebsocketConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebsocketConnectionStatus, arg.Status, arg.ID)
	return err
}

const updateWebsocketConnectionSubscriptionCount = `-- name: UpdateWebsocketConnectionSubscriptionCount :exec
UPDATE websocket_connections
SET subscription_count = $1::int,
    updated_at = NOW()
WHERE id = $2::uuid
`

type UpdateWebsocketConnectionSubscriptionCountParams struct {
	SubscriptionCount int32     `json:"subscription_count"`
	ID                uuid.UUID `json:"id"`
}

func (q *Queries) UpdateWebsocketConnectionSubscriptionCount(ctx context.Context, arg UpdateWebsocketConnectionSubscriptionCountParams) error {
	_, err := q.db.Exec(ctx, updateWebsocketConnectionSubscriptionCount, arg.SubscriptionCount, arg.ID)
	return err
}
