// Code generated by kessoku. DO NOT EDIT.

package main

import (
	"context"
	"github.com/mazrean/kessoku"
	"github.com/pickle.pw/monolith/internal/api"
	"github.com/pickle.pw/monolith/internal/clients"
	"github.com/pickle.pw/monolith/internal/handlers"
	"github.com/pickle.pw/monolith/internal/logger"
	"github.com/pickle.pw/monolith/internal/schedulers"
	"github.com/pickle.pw/monolith/internal/services"
	"github.com/pickle.pw/monolith/internal/storage"
	"github.com/pickle.pw/monolith/internal/usecases"
)

func InitializeAPI(ctx context.Context) (api.PickleAPI, error) {
	var err error
	sugaredLogger, err := kessoku.Provide(logger.NewLogger).Fn()()
	if err != nil {
		var zero api.PickleAPI
		return zero, err
	}
	oryAPI := kessoku.Provide(clients.NewOryAPI).Fn()(sugaredLogger)
	var err0 error
	elasticStorage, err0 := kessoku.Provide(storage.NewElasticStorage).Fn()(sugaredLogger)
	if err0 != nil {
		var zero api.PickleAPI
		return zero, err0
	}
	var err1 error
	cacheStorage, err1 := kessoku.Provide(storage.NewCacheStorage).Fn()(sugaredLogger)
	if err1 != nil {
		var zero api.PickleAPI
		return zero, err1
	}
	ordersBrokerService := kessoku.Provide(services.NewOrdersBrokerService).Fn()(sugaredLogger)
	igdbclient := kessoku.Provide(clients.NewIGDBClient).Fn()(sugaredLogger)
	tmdbclient := kessoku.Provide(clients.NewTMDBClient).Fn()(sugaredLogger)
	imageService := kessoku.Provide(services.NewImageService).Fn()(sugaredLogger)
	var err2 error
	relationalStorage, _, err2 := kessoku.Provide(storage.NewRelationalStorage).Fn()(ctx, sugaredLogger)
	if err2 != nil {
		var zero api.PickleAPI
		return zero, err2
	}
	var err3 error
	fileStorage, err3 := kessoku.Provide(storage.NewFileStorage).Fn()(ctx, sugaredLogger)
	if err3 != nil {
		var zero api.PickleAPI
		return zero, err3
	}
	statusHandler := kessoku.Provide(handlers.NewStatusHandler).Fn()(relationalStorage, elasticStorage, cacheStorage, sugaredLogger)
	migrationService := kessoku.Provide(services.NewMigrationService).Fn()(relationalStorage, elasticStorage, sugaredLogger)
	igdbsyncService := kessoku.Provide(services.NewIGDBSyncService).Fn()(relationalStorage, elasticStorage, igdbclient, sugaredLogger)
	tmdbsyncService := kessoku.Provide(services.NewTMDBSyncService).Fn()(relationalStorage, elasticStorage, tmdbclient, sugaredLogger)
	followerService := kessoku.Provide(services.NewFollowerService).Fn()(relationalStorage, cacheStorage, sugaredLogger)
	contentNoteReactionService := kessoku.Provide(services.NewContentNoteReactionService).Fn()(relationalStorage, sugaredLogger)
	avatarService := kessoku.Provide(services.NewAvatarService).Fn()(relationalStorage, cacheStorage, fileStorage, imageService, sugaredLogger)
	igdbscheduler := kessoku.Provide(schedulers.NewIGDBScheduler).Fn()(igdbsyncService, relationalStorage, sugaredLogger)
	tmdbscheduler := kessoku.Provide(schedulers.NewTMDBScheduler).Fn()(tmdbsyncService, relationalStorage, sugaredLogger)
	followerHandler := kessoku.Provide(handlers.NewFollowerHandler).Fn()(followerService, sugaredLogger)
	userService := kessoku.Provide(services.NewUserService).Fn()(relationalStorage, fileStorage, cacheStorage, avatarService, followerService, sugaredLogger)
	ordererService := kessoku.Provide(services.NewOrdererService).Fn()(relationalStorage, userService, sugaredLogger)
	posterService := kessoku.Provide(services.NewPosterService).Fn()(relationalStorage, fileStorage, cacheStorage, imageService, userService, sugaredLogger)
	moderatorService := kessoku.Provide(services.NewModeratorService).Fn()(relationalStorage, cacheStorage, avatarService, userService, sugaredLogger)
	posterHandler := kessoku.Provide(handlers.NewPosterHandler).Fn()(posterService, sugaredLogger)
	contentService := kessoku.Provide(services.NewContentService).Fn()(relationalStorage, elasticStorage, posterService, sugaredLogger)
	permissionService := kessoku.Provide(services.NewPermissionService).Fn()(moderatorService, sugaredLogger)
	moderatorHandler := kessoku.Provide(handlers.NewModeratorHandler).Fn()(moderatorService, userService, avatarService, permissionService, sugaredLogger)
	contentNoteService := kessoku.Provide(services.NewContentNoteService).Fn()(relationalStorage, elasticStorage, cacheStorage, posterService, ordererService, permissionService, contentService, userService, sugaredLogger)
	collectionService := kessoku.Provide(services.NewCollectionService).Fn()(relationalStorage, cacheStorage, permissionService, sugaredLogger)
	contentHandler := kessoku.Provide(handlers.NewContentHandler).Fn()(elasticStorage, contentNoteService, contentService, sugaredLogger)
	orderService := kessoku.Provide(services.NewOrderService).Fn()(relationalStorage, userService, ordererService, contentNoteService, permissionService, ordersBrokerService, sugaredLogger)
	createContentNoteUseCase := kessoku.Provide(usecases.NewCreateContentNoteUseCase).Fn()(relationalStorage, contentNoteService, permissionService, userService, ordererService, contentService, avatarService, sugaredLogger)
	getSortedContentNotesByUserIDUseCase := kessoku.Provide(usecases.NewGetSortedContentNotesByUserIDUseCase).Fn()(contentNoteService, contentService, avatarService, sugaredLogger)
	collectionHandler := kessoku.Provide(handlers.NewCollectionHandler).Fn()(collectionService, contentNoteService, contentService, permissionService, sugaredLogger)
	profileService := kessoku.Provide(services.NewProfileService).Fn()(avatarService, followerService, moderatorService, orderService, userService, contentNoteService, sugaredLogger)
	createOrderUseCase := kessoku.Provide(usecases.NewCreateOrderUseCase).Fn()(relationalStorage, userService, orderService, ordererService, contentService, ordersBrokerService, sugaredLogger)
	contentNoteHandler := kessoku.Provide(handlers.NewContentNoteHandler).Fn()(orderService, ordererService, posterService, permissionService, avatarService, contentNoteService, contentNoteReactionService, contentService, createContentNoteUseCase, getSortedContentNotesByUserIDUseCase, sugaredLogger)
	profileHandler := kessoku.Provide(handlers.NewProfileHandler).Fn()(userService, profileService, avatarService, orderService, followerService, sugaredLogger)
	profileEventsHandler := kessoku.Provide(handlers.NewProfileEventsHandler).Fn()(profileService, ordersBrokerService, sugaredLogger)
	getUserByIDUseCase := kessoku.Provide(usecases.NewGetUserByIDUseCase).Fn()(userService, avatarService, profileService, sugaredLogger)
	orderHandler := kessoku.Provide(handlers.NewOrdersHandler).Fn()(relationalStorage, userService, orderService, ordererService, avatarService, contentService, contentNoteService, permissionService, ordersBrokerService, createOrderUseCase, sugaredLogger)
	userHandler := kessoku.Provide(handlers.NewUserHandler).Fn()(relationalStorage, userService, avatarService, getUserByIDUseCase, ordererService, sugaredLogger)
	pickleAPI := kessoku.Provide(api.NewPickleAPI).Fn()(userHandler, profileHandler, statusHandler, orderHandler, contentNoteHandler, posterHandler, migrationService, contentHandler, collectionHandler, moderatorHandler, profileEventsHandler, igdbscheduler, igdbsyncService, tmdbscheduler, tmdbsyncService, oryAPI, followerHandler, sugaredLogger)
	return pickleAPI, nil
}
