// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/pickle.pw/monolith/internal/api"
	"github.com/pickle.pw/monolith/internal/handlers"
	"github.com/pickle.pw/monolith/internal/services"
	"github.com/pickle.pw/monolith/internal/storage"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeAPI(ctx context.Context) (api.PickleAPI, func(), error) {
	sqlDatabase, cleanup, err := storage.NewPGXPoolWithCleanup(ctx)
	if err != nil {
		return nil, nil, err
	}
	s3Client, err := storage.NewS3Client(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacheClient, err := storage.NewCacheClient(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	imageService := services.NewImageService()
	avatarService := services.NewAvatarService(sqlDatabase, cacheClient, s3Client, imageService)
	profileService := services.NewProfileService(sqlDatabase, s3Client, cacheClient, avatarService)
	profileHandler := handlers.NewUserHandler(profileService, avatarService)
	elasticClient, err := storage.NewElasticClient()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	supabaseClient, err := storage.NewSupabaseClient(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	statusService := services.NewStatusService(supabaseClient, s3Client)
	statusHandler := handlers.NewStatusHandler(sqlDatabase, elasticClient, cacheClient, statusService)
	ordererService := services.NewOrdererService(sqlDatabase)
	gameNoteOrderService := services.NewGameNoteOrderService(sqlDatabase)
	orderService := services.NewOrderService(sqlDatabase, profileService, ordererService, gameNoteOrderService)
	orderHandler := handlers.NewOrdersHandler(orderService, profileService)
	contentService := services.NewContentService(elasticClient)
	posterService := services.NewPosterService(sqlDatabase, s3Client, cacheClient, imageService, profileService)
	gameNoteService := services.NewGameNoteService(sqlDatabase, elasticClient, cacheClient, orderService, profileService, ordererService, contentService, gameNoteOrderService, posterService)
	gameNoteHandler := handlers.NewGameNoteHandler(profileService, gameNoteService, orderService, posterService)
	posterHandler := handlers.NewPosterHandler(posterService)
	migrationService := services.NewMigrationService(sqlDatabase, elasticClient)
	contentHandler := handlers.NewContentHandler(contentService)
	pickleAPI := api.NewPickleAPI(profileHandler, statusHandler, orderHandler, gameNoteHandler, posterHandler, migrationService, contentHandler)
	return pickleAPI, func() {
		cleanup()
	}, nil
}
