// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/pickle.pw/monolith/internal/api"
	"github.com/pickle.pw/monolith/internal/clients"
	"github.com/pickle.pw/monolith/internal/handlers"
	"github.com/pickle.pw/monolith/internal/schedulers"
	"github.com/pickle.pw/monolith/internal/services"
	"github.com/pickle.pw/monolith/internal/storage"
)

import (
	_ "github.com/joho/godotenv/autoload"
	_ "github.com/pickle.pw/monolith/docs"
)

// Injectors from wire.go:

func InitializeAPI(ctx context.Context) (api.PickleAPI, func(), error) {
	relationalStorage, cleanup, err := storage.NewRelationalStorage(ctx)
	if err != nil {
		return nil, nil, err
	}
	fileStorage, err := storage.NewFileStorage(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacheStorage, err := storage.NewCacheStorage(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	imageService := services.NewImageService()
	avatarService := services.NewAvatarService(relationalStorage, cacheStorage, fileStorage, imageService)
	followerService := services.NewFollowerService(relationalStorage, cacheStorage)
	ordererService := services.NewOrdererService(relationalStorage)
	profileService := services.NewProfileService(relationalStorage, fileStorage, cacheStorage, avatarService, followerService, ordererService)
	elasticStorage, err := storage.NewElasticStorage(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	posterService := services.NewPosterService(relationalStorage, fileStorage, cacheStorage, imageService, profileService)
	moderatorService := services.NewModeratorService(relationalStorage, cacheStorage, avatarService, profileService)
	permissionService := services.NewPermissionService(moderatorService)
	gameService := services.NewGameService(relationalStorage)
	movieService := services.NewMovieService(relationalStorage)
	contentNoteService := services.NewContentNoteService(relationalStorage, elasticStorage, cacheStorage, posterService, ordererService, permissionService, profileService, gameService, movieService)
	ordersBrokerService := services.NewOrdersBrokerService()
	orderService := services.NewOrderService(relationalStorage, profileService, ordererService, contentNoteService, permissionService, ordersBrokerService)
	publicProfileService := services.NewPublicProfileService(avatarService, followerService, moderatorService, orderService, profileService, contentNoteService)
	profileHandler := handlers.NewUserHandler(profileService, avatarService, orderService, followerService, publicProfileService)
	statusHandler := handlers.NewStatusHandler(relationalStorage, elasticStorage, cacheStorage)
	orderHandler := handlers.NewOrdersHandler(orderService, profileService, contentNoteService)
	contentNoteReactionService := services.NewContentNoteReactionService(relationalStorage)
	contentNoteHandler := handlers.NewContentNoteHandler(profileService, orderService, posterService, contentNoteService, contentNoteReactionService)
	posterHandler := handlers.NewPosterHandler(posterService)
	migrationService := services.NewMigrationService(relationalStorage, elasticStorage)
	contentService := services.NewContentService(relationalStorage, elasticStorage, posterService, gameService, movieService)
	contentHandler := handlers.NewContentHandler(elasticStorage, contentNoteService, contentService)
	collectionService := services.NewCollectionService(relationalStorage, cacheStorage, permissionService)
	collectionHandler := handlers.NewCollectionHandler(collectionService, contentNoteService, posterService)
	moderatorHandler := handlers.NewModeratorHandler(moderatorService, profileService)
	profileEventsHandler := handlers.NewProfileEventsHandler(profileService)
	igdbClient := clients.NewIGDBClient()
	igdbSyncService := services.NewIGDBSyncService(relationalStorage, elasticStorage, igdbClient)
	igdbScheduler := schedulers.NewIGDBScheduler(igdbSyncService, relationalStorage)
	tmdbClient := clients.NewTMDBClient()
	tmdbSyncService := services.NewTMDBSyncService(relationalStorage, elasticStorage, tmdbClient)
	tmdbScheduler := schedulers.NewTMDBScheduler(tmdbSyncService, relationalStorage)
	oryAPI, err := clients.NewOryAPI(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pickleAPI := api.NewPickleAPI(profileHandler, statusHandler, orderHandler, contentNoteHandler, posterHandler, migrationService, contentHandler, collectionHandler, moderatorHandler, profileEventsHandler, igdbScheduler, igdbSyncService, tmdbScheduler, tmdbSyncService, oryAPI)
	return pickleAPI, func() {
		cleanup()
	}, nil
}
